// Auto-generated from crawled menu structure
module.exports = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'FPT Cloud Server',
          className: 'sidebar-migrated',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Tagging',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'tagging/initial-setup', label: 'Initial Setup' },
            { type: 'doc', id: 'tagging/create-tag-new', label: 'Create a new tag' },
            { type: 'doc', id: 'tagging/edit-tag', label: 'Edit tags' },
            { type: 'doc', id: 'tagging/delete-tag', label: 'Delete a tag' },
            {
              type: 'category',
              label: 'Manage tags for resources',
              collapsed: true,
              items: [
                { type: 'doc', id: 'tagging/resource-1', label: 'Manage tags for resources' },
                { type: 'doc', id: 'tagging/tags-instance', label: 'Manage tags for Instance' },
                { type: 'doc', id: 'tagging/tags-storage-disk', label: 'Manage tags for Storage Disk' },
                { type: 'doc', id: 'tagging/tags-snapshot', label: 'Manage tags for Snapshot' },
                { type: 'doc', id: 'tagging/tags-custom-image', label: 'Manage tags for Custom Image' },
                { type: 'doc', id: 'tagging/tags-floating-ip', label: 'Manage tags for Floating IP' },
                { type: 'doc', id: 'tagging/tags-subnet', label: 'Manage tags for Subnet' },
                { type: 'doc', id: 'tagging/tags-security-group', label: 'Manage tags for Security Group' },
                { type: 'doc', id: 'tagging/tagg-lb', label: 'Manage tag for Load Balancer' },
              ],
            },
            { type: 'doc', id: 'tagging/tagging-billing', label: 'Tagging billing' },
          ],
        },
        {
          type: 'category',
          label: 'Cloud Server',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'cloud-server/Initial-Setup', label: 'Initial Setup' },
            {
              type: 'category',
              label: 'Create a Virtual Machine',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/quick-starts-tao-mot-may-ao', label: 'Create a virtual machine' },
                { type: 'doc', id: 'cloud-server/create-vm-iso', label: 'Notes for creating VM from ISO' },
              ],
            },
            { type: 'doc', id: 'cloud-server/clone-instance', label: 'Clone a virtual machine' },
            { type: 'doc', id: 'cloud-server/quick-starts-tatbat-may-ao', label: 'Power on/off virtual machine' },
            { type: 'doc', id: 'cloud-server/quick-starts-khoi-dong-lai-may-ao', label: 'Reboot virtual machine' },
            { type: 'doc', id: 'cloud-server/lock-unlock-instance-deletion', label: 'Lock & Unlock VM deletion' },
            { type: 'doc', id: 'cloud-server/quick-starts-xoa-may-ao', label: 'Delete a virtual machine' },
            {
              type: 'category',
              label: 'Manage Virtual Machines',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/quan-ly-may-ao', label: 'Manage virtual machines' },
                { type: 'doc', id: 'cloud-server/tutorials-khoi-tao-mot-may-ao-moi', label: 'Create a new virtual machine' },
                { type: 'doc', id: 'cloud-server/tutorials-ket-noi-vao-may-ao-windows', label: 'Connect to Windows VM' },
                { type: 'doc', id: 'cloud-server/tutorials-ket-noi-vao-may-ao-linux', label: 'Connect to Linux VM' },
                { type: 'doc', id: 'cloud-server/attach-a-network-card-to-the-virtual-machine', label: 'Attach NIC to virtual machine' },
                { type: 'doc', id: 'cloud-server/remove-the-network-card-from-the-virtual-machine', label: 'Remove NIC from virtual machine' },
                { type: 'doc', id: 'cloud-server/tutorials-tra-cuu-thong-tin-thong-so-ky-thuat-cua-may-ao-da-tao', label: 'View VM details' },
                { type: 'doc', id: 'cloud-server/tutorials-thay-doi-thong-tin-cau-hinh-may-chu', label: 'Change VM configuration' },
                { type: 'doc', id: 'cloud-server/tutorials-backup-may-chu-voi-snapshot', label: 'Backup VM with Snapshot' },
                { type: 'doc', id: 'cloud-server/tutorials-xoa-may-ao', label: 'Delete a virtual machine' },
              ],
            },
            {
              type: 'category',
              label: 'GPU with Portal Console',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/GPU', label: 'GPU with Portal Console' },
                { type: 'doc', id: 'cloud-server/gpu-general', label: 'GPU management (General)' },
                { type: 'doc', id: 'cloud-server/gpu-specific', label: 'GPU management (Specific)' },
              ],
            },
            {
              type: 'category',
              label: 'GPU Server with HPC Portal',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/quan-ly-gpu-voi-hpc-portal', label: 'GPU Server with HPC Portal' },
                { type: 'doc', id: 'cloud-server/hpc-quick-start', label: 'Quick start' },
                { type: 'doc', id: 'cloud-server/hpc-change-package', label: 'Change package' },
                { type: 'doc', id: 'cloud-server/hpc-fixed-rental', label: 'Fixed rental' },
                { type: 'doc', id: 'cloud-server/hpc-snapshot-backup', label: 'Snapshot backup' },
                { type: 'doc', id: 'cloud-server/hpc-hardware-fixation', label: 'Hardware fixation' },
                { type: 'doc', id: 'cloud-server/hpc-rest-machine', label: 'Reset machine' },
                { type: 'doc', id: 'cloud-server/hpc-schedule-shutdown', label: 'Schedule shutdown' },
                { type: 'doc', id: 'cloud-server/hpc-clone-image', label: 'Clone image' },
                { type: 'doc', id: 'cloud-server/hpc-level-2-password', label: 'Level 2 password' },
                { type: 'doc', id: 'cloud-server/hpc-delete-image', label: 'Delete image' },
              ],
            },
            {
              type: 'category',
              label: 'Block Storage',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/block-storage', label: 'Block Storage' },
                { type: 'doc', id: 'cloud-server/tao-storage-disk', label: 'Create Storage Disk' },
                { type: 'doc', id: 'cloud-server/gan-storage-disk-vao-may-ao', label: 'Attach Storage Disk to VM' },
                { type: 'doc', id: 'cloud-server/cau-hinh-o-dia-cho-may-ao-chay-windows', label: 'Configure disk for Windows VM' },
                { type: 'doc', id: 'cloud-server/go-storage-disk-khoi-may-ao', label: 'Detach Storage Disk from VM' },
                { type: 'doc', id: 'cloud-server/edit-storage-disk', label: 'Edit Storage Disk' },
                { type: 'doc', id: 'cloud-server/xoa-storage-disk', label: 'Delete Storage Disk' },
              ],
            },
            { type: 'doc', id: 'cloud-server/profile-ssh-key', label: 'SSH Key' },
            {
              type: 'category',
              label: 'Token',
          className: 'sidebar-migrated',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/token', label: 'Token' },
                { type: 'doc', id: 'cloud-server/create-token', label: 'Create Token' },
                { type: 'doc', id: 'cloud-server/revoke-token', label: 'Revoke Token' },
                { type: 'doc', id: 'cloud-server/FQAs', label: 'FAQs' },
                { type: 'doc', id: 'cloud-server/custom-images-overview', label: 'Custom Images Overview' },
                { type: 'doc', id: 'cloud-server/tai-len-custom-image', label: 'Upload Custom Image' },
                { type: 'doc', id: 'cloud-server/xoa-custom-image', label: 'Delete Custom Image' },
              ],
            },
            {
              type: 'category',
              label: 'Instance Template',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/tutorials-quan-ly-instance-template', label: 'Manage Instance Template' },
                { type: 'doc', id: 'cloud-server/tutorials-khoi-tao-template-tu-may-ao', label: 'Create template from VM' },
                { type: 'doc', id: 'cloud-server/tutorials-quan-ly-template-duoc-tao-tu-may-ao', label: 'Manage templates on Custom Images' },
                { type: 'doc', id: 'cloud-server/tutorials-tao-instance-tu-template', label: 'Create Instance from template' },
                { type: 'doc', id: 'cloud-server/tutorials-xoa-template', label: 'Delete template' },
              ],
            },
            { type: 'doc', id: 'cloud-server/nat-instance', label: 'NAT Instance' },
            {
              type: 'category',
              label: 'NIC (Network Interface Card)',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/NIC-overview-1', label: 'NIC Management' },
                { type: 'doc', id: 'cloud-server/overview-nic', label: 'Overview' },
                { type: 'doc', id: 'cloud-server/create-card-NIC- Primary', label: 'Create Primary NIC' },
                { type: 'doc', id: 'cloud-server/disable-NIC-card', label: 'Disable NIC' },
                { type: 'doc', id: 'cloud-server/enable-NIC-card', label: 'Enable NIC' },
                { type: 'doc', id: 'cloud-server/add-card-NIC- new', label: 'Add new NIC' },
                { type: 'doc', id: 'cloud-server/convert-card', label: 'Convert to Primary' },
                { type: 'doc', id: 'cloud-server/edit-ip-address', label: 'Edit IP Address' },
                { type: 'doc', id: 'cloud-server/change-address-MAC', label: 'Change MAC Address' },
                { type: 'doc', id: 'cloud-server/delete-card-NIC', label: 'Delete NIC' },
                { type: 'doc', id: 'cloud-server/change-network-config', label: 'Change Network Config' },
              ],
            },
            {
              type: 'category',
              label: 'Networking',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/network-all', label: 'Networking Overview' },
                { type: 'doc', id: 'cloud-server/networking-overview', label: 'Networking Details' },
                { type: 'doc', id: 'cloud-server/gateway', label: 'Gateway' },
                { type: 'doc', id: 'cloud-server/quan-ly-floating-ip', label: 'Manage Floating IP' },
                { type: 'doc', id: 'cloud-server/Quản lý Subnets', label: 'Manage Subnets' },
                { type: 'doc', id: 'cloud-server/allow-address-pair', label: 'Allow Address Pair' },
              ],
            },
            {
              type: 'category',
              label: 'Security Group',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/quan-ly-security-group', label: 'Manage Security Group' },
                { type: 'doc', id: 'cloud-server/security-group-filter', label: 'Filter Security Group' },
                { type: 'doc', id: 'cloud-server/security-group-priority-rule', label: 'Priority Rule' },
              ],
            },
            { type: 'doc', id: 'cloud-server/terraform', label: 'IaC (Terraform)' },
            {
              type: 'category',
              label: 'Instance Group — Affinity & Anti-Affinity',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/instance-group', label: 'Instance Group overview' },
                { type: 'doc', id: 'cloud-server/overview-affinity', label: 'Introduction' },
                { type: 'doc', id: 'cloud-server/create-instance-group', label: 'Create Instance Group' },
                { type: 'doc', id: 'cloud-server/edit-instance-group-specific', label: 'Edit Instance Group' },
                { type: 'doc', id: 'cloud-server/add-instance-instance-group', label: 'Add VM to Instance Group' },
                { type: 'doc', id: 'cloud-server/delete-instance-group', label: 'Delete Instance Group' },
              ],
            },
            { type: 'doc', id: 'cloud-server/overview-bell', label: 'Notification Bell' },
            {
              type: 'category',
              label: 'Project Management',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/project-structure', label: 'Project Management' },
                { type: 'doc', id: 'cloud-server/quan-ly-project', label: 'Manage Projects' },
                { type: 'doc', id: 'cloud-server/select-project-when-creating-VPC', label: 'Select Project when creating VPC' },
                { type: 'doc', id: 'cloud-server/header-project', label: 'Change header UI' },
              ],
            },
            { type: 'doc', id: 'cloud-server/new-quota', label: 'PAYG billing' },
            {
              type: 'category',
              label: 'Auto Schedule on/off Instance',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/instance-schedule', label: 'Instance Schedule' },
                { type: 'doc', id: 'cloud-server/schedule-overview', label: 'Schedule Overview' },
                { type: 'doc', id: 'cloud-server/create-new-instance', label: 'Create schedule' },
                { type: 'doc', id: 'cloud-server/view-detail-instance', label: 'View schedule details' },
                { type: 'doc', id: 'cloud-server/attach-schedule-to-instance', label: 'Attach VMs to schedule' },
                { type: 'doc', id: 'cloud-server/detach-schedule-to-instance', label: 'Detach VMs from schedule' },
                { type: 'doc', id: 'cloud-server/delete-instance-schedule', label: 'Delete schedule' },
              ],
            },
            {
              type: 'category',
              label: 'VM Snapshot Schedule',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/schedule-snapshotVM', label: 'VM Snapshot Schedule' },
                { type: 'doc', id: 'cloud-server/create-schedule-snapshotVM', label: 'Create schedule' },
                { type: 'doc', id: 'cloud-server/viewschedule-snapshotVM', label: 'View details' },
                { type: 'doc', id: 'cloud-server/editschedule-snapshotVM', label: 'Edit schedule' },
                { type: 'doc', id: 'cloud-server/deleteschedule-snapshotVM', label: 'Delete schedule' },
              ],
            },
            {
              type: 'category',
              label: 'Storage Snapshot Schedule',
              collapsed: true,
              items: [
                { type: 'doc', id: 'cloud-server/schedule-snapshotstorage', label: 'Storage Snapshot Schedule' },
                { type: 'doc', id: 'cloud-server/createschedule-snapshotstorage', label: 'Create schedule' },
                { type: 'doc', id: 'cloud-server/viewschedule-snapshotstorage', label: 'View details' },
                { type: 'doc', id: 'cloud-server/editschedule-snapshotstorage', label: 'Edit schedule' },
                { type: 'doc', id: 'cloud-server/deleteschedule-snapshotstorage', label: 'Delete schedule' },
              ],
            },
            { type: 'doc', id: 'cloud-server/question-2', label: 'FAQ: Customize Security Group rules' },
            { type: 'doc', id: 'cloud-server/question-1', label: 'FAQ: Edit Address Pairs' },
          ],
        },
        {
          type: 'category',
          label: 'FPT Cloud Portal',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-cloud-portal/fpt-cloud-portal', label: 'FPT Cloud Portal' }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'FPT Container',
          className: 'sidebar-migrated',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Managed - FPT Kubernetes Engine',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/initial-setup', label: 'Initial Setup' },
            {
              type: 'category',
              label: 'Managing K8s Cluster',
              collapsed: true,
              items: [
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/managing-k8s-cluster', label: 'Managing K8s Cluster' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/create-new-k8s-cluster', label: 'Create a New K8s Cluster' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/list-created-cluster', label: 'List Created Clusters' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/access-clusters-detail-information', label: 'Access Cluster’s Detail Informations' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/get-cluster-access-information', label: 'Get Cluster\'s Access Information' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/delete-k8s-cluster', label: 'Delete a K8s Cluster' },
              ],
            },
            {
              type: 'category',
              label: 'Changing Cluster’s Configuration',
              collapsed: true,
              items: [
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/changing-clusters-configuration', label: 'Changing Cluster’s Configuration' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/add-worker-group', label: 'Add Worker Group' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/change-worker-groups-configuration', label: 'Change Worker Group’s Configuration' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/upgrade-k8s-version', label: 'Upgrade K8s Version' },
              ],
            },
            {
              type: 'category',
              label: 'Cluster Autoscale',
              collapsed: true,
              items: [
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/cluster-autoscale', label: 'Cluster Autoscale' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/enable-cluster-autoscale', label: 'Enable Cluster Autoscale' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/disable-cluster-autoscale', label: 'Disable Cluster Autoscale' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/modify-cluster-autoscale-configuration', label: 'Modify Cluster Autoscale Configuration' },
              ],
            },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/deploy-application-in-worker-pool', label: 'Deploy an Application in a Worker Pool' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/load-balancer-services', label: 'Load Balancer Services' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/persistent-storage', label: 'Persistent Storage' },
            {
              type: 'category',
              label: 'How to use GPU in Kubernetes',
              collapsed: true,
              items: [
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/how-to-use-gpu-in-kubernetes', label: 'How to use GPU in Kubernetes' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/setup-k8s-cluster-for-gpu-usage', label: 'Setting up K8s Cluster with GPU' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/addding-gpu-worker-group', label: 'Adding GPU Worker Group' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/deploy-application-with-gpu-on-k8s', label: 'Deploy an Application with GPU Workload on K8s' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/setting-up-gpu-telemetry', label: 'Setting up GPU Telemetry' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/container-level-auto-scaling', label: 'Container-level Auto-scaling' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/node-level-auto-scaling', label: 'Node-level Auto-scaling' },
              ],
            },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/notes-when-using-mfke', label: 'Notes when using M-FKE' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/faqs-mfke', label: 'FAQs' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/microservices-architecture-on-fke', label: 'Micro-services Architecture on FKE' },
            {
              type: 'category',
              label: 'GPU on FPT Cloud',
              collapsed: true,
              items: [
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/gpu-fpt-cloud', label: 'GPU on FPT Cloud' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/what-is-gpu', label: 'What is a GPU?' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/why-you-should-use-gpu-in-cloud', label: 'Why you should use GPU in cloud?' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/why-you-should-use-gpu-in-k8s', label: 'Why you should use GPU in K8s?' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/gpu-sharing', label: 'GPU Sharing' },
                { type: 'doc', id: 'managed-fpt-kubernetes-engine/gpu-fpt-cloud-k8s', label: 'GPU on FPT Cloud\'s K8s' },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'FPT Container Registry',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-container-registry/initial-setup', label: 'Initial Setup' },
            { type: 'doc', id: 'fpt-container-registry/enabling-fpt-container-registry-service', label: 'Enabling FPT Container Registry Service' },
            {
              type: 'category',
              label: 'Docker CLI',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-container-registry/docker-cli', label: 'Docker CLI' },
                { type: 'doc', id: 'fpt-container-registry/docker-login', label: 'Docker Login' },
                { type: 'doc', id: 'fpt-container-registry/tagging-and-pushing-images-to-fpt-container-registry', label: 'Tagging and Pushing Images to FPT Container Registry' },
                { type: 'doc', id: 'fpt-container-registry/pulling-docker-image-from-fpt-container-registry-to-local', label: 'Pulling Docker Image from FPT Container Registry to local' },
              ],
            },
            {
              type: 'category',
              label: 'Managing Repositories on the FPT Cloud Portal',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-container-registry/managing-repositories-on-the-fpt-cloud-portal', label: 'Managing Repositories on the FPT Cloud Portal' },
                { type: 'doc', id: 'fpt-container-registry/view-repositories-list', label: 'View Repositories List' },
                { type: 'doc', id: 'fpt-container-registry/deleting-an-image-or-artifact-in-a-repository', label: 'Deleting an Image or Artifact in a Repository' },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'FPT App Catalogs',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-app-catalogs/initial-setup', label: 'Initial Setup' },
            { type: 'doc', id: 'fpt-app-catalogs/create-a-new-fpt-app-catalogs', label: 'Create a new FPT App Catalogs' },
            { type: 'doc', id: 'fpt-app-catalogs/view-app-catalog-details', label: 'View App Catalog details' },
            { type: 'doc', id: 'fpt-app-catalogs/add-cluster-to-app-catalogs-management', label: 'Add K8s cluster to App Catalogs Management' },
            {
              type: 'category',
              label: 'Manage App Catalogs',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-app-catalogs/manage-app-catalogs', label: 'Manage App Catalogs' },
                { type: 'doc', id: 'fpt-app-catalogs/search-app-catalogs-from-a-repository', label: 'Search App Catalogs from a repository' },
                { type: 'doc', id: 'fpt-app-catalogs/deploy-app-catalogs-to-cluster', label: 'Deploy App Catalogs to Cluster' },
              ],
            },
            {
              type: 'category',
              label: 'Manage Deployed Applications',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-app-catalogs/manage-deployed-applications', label: 'Manage Deployed Applications' },
                { type: 'doc', id: 'fpt-app-catalogs/filter-deployed-appplications-by-cluster', label: 'Filter Deployed Appplications by Cluster' },
                { type: 'doc', id: 'fpt-app-catalogs/view-deployed-applications-details', label: 'View a Deployed Application\'s Details' },
                { type: 'doc', id: 'fpt-app-catalogs/change-applications-configuration', label: 'Change Application\'s Configuration' },
                { type: 'doc', id: 'fpt-app-catalogs/rollback-an-application-to-the-old-configuration', label: 'Rollback an Application to the old configuration' },
                { type: 'doc', id: 'fpt-app-catalogs/upgrade-applications-to-the-latest-version', label: 'Upgrade Applications to the Latest Version' },
                { type: 'doc', id: 'fpt-app-catalogs/uninstall-applications', label: 'Uninstall Applications' },
              ],
            },
            { type: 'doc', id: 'fpt-app-catalogs/delete-an-app-catalogs-mangement', label: 'Delete an App Catalogs Mangement' },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated – FPT Kubernetes Engine',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/initial-setup', label: 'Initial Setup' },
            {
              type: 'category',
              label: 'Managing K8s Cluster',
              collapsed: true,
              items: [
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/managing-k8s-cluster', label: 'Managing K8s Cluster' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/create-new-k8s-cluster', label: 'Create a new K8s Cluster' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/list-created-clusters', label: 'List Created Clusters' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/access-clusters-detail-information', label: 'Access Cluster’s Detail Informations' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/get-cluster-access-information', label: 'Get Cluster\'s Access Information' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/delete-k8s-cluster', label: 'Delete a K8s Cluster' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/stop-k8s-cluster', label: 'Stop a K8s Cluster' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/start-k8s-cluster', label: 'Start a K8s Cluster' },
              ],
            },
            {
              type: 'category',
              label: 'Changing Cluster\'s Configuration',
              collapsed: true,
              items: [
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/changing-cluster-configuration', label: 'Changing Cluster\'s Configuration' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/scale-worker-nodes', label: 'Scale Worker Nodes' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/change-nodes-configuration', label: 'Change Nodes\' Configuration' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/change-nfs-server-configuration', label: 'Change NFS Server\'s Configuration' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/increase-storage-size-of-nodes', label: 'Increase Storage Size of Nodes' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/increase-storage-size-of-nfs-server', label: 'Increase Storage Size of NFS Server' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/upgrading-k8s-version', label: 'Upgrading K8s Version' },
                { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/add-nfs-storage', label: 'Add NFS Storage' },
              ],
            },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/auto-scale', label: 'AutoScale' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/persistent-storage', label: 'Persistent Storage' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/load-balancer-services', label: 'Load Balancer Services' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/advanced-firewall', label: 'Advanced Firewall' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/backup-restore-cluster', label: 'Backup & Restore Cluster' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/notes-when-using-dfke', label: 'Notes when using D-FKE' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/faqs', label: 'FAQs' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'FPT Network',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'VPN Site-to-Site',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'vpn-site-to-site/create-vpn', label: 'Site to Site VPN Initialization' },
            { type: 'doc', id: 'vpn-site-to-site/disable-VPN-Site-to-Site', label: 'Disable VPN-Site-to-Site' },
            { type: 'doc', id: 'vpn-site-to-site/enable-vpn-s2S', label: 'Enable VPN-Site-to-Site' },
            { type: 'doc', id: 'vpn-site-to-site/edit-vpn', label: 'Edit VPN Information' },
            { type: 'doc', id: 'vpn-site-to-site/edit-security-profile', label: 'Edit Security Profile' },
            { type: 'doc', id: 'vpn-site-to-site/delete-vpn', label: 'Delete VPN Site-to-Site' },
            { type: 'doc', id: 'vpn-site-to-site/VPN-Activity', label: 'VPN-Activity' },
            { type: 'doc', id: 'vpn-site-to-site/Authenticate-Certificate mode-1', label: 'Authenticate-Certificate mode' },
            {
              type: 'category',
              label: 'Common VPN Device Configuration',
              collapsed: true,
              items: [
                { type: 'doc', id: 'vpn-site-to-site/common-vpn-device-configuration', label: 'Common VPN Device Configuration' },
                { type: 'doc', id: 'vpn-site-to-site/VPN-Site-to-Site-Configuration-with-Palo-Alto-guide', label: 'VPN Site-to-Site Configuration with Palo Alto' },
                { type: 'doc', id: 'vpn-site-to-site/VPN-Site-to-Site-Configuration-with-Fortigate-guide', label: 'VPN Site-to-Site Configuration with Fortigate' },
                { type: 'doc', id: 'vpn-site-to-site/VPN-Site-to-Site-Configuration-between-FCI-and-AWS-(Virtual-private-gateways)-guide', label: 'VPN Site-to-Site Configuration between FCI and AWS (Virtual private gateways)' },
                { type: 'doc', id: 'vpn-site-to-site/VPN-Site-to-Site-Configuration-between-FCI-and-AWS-(transit-gateway)-guide', label: 'VPN Site-to-Site Configuration between FCI and AWS (Transit-Gateway)' },
                { type: 'doc', id: 'vpn-site-to-site/openstack-portal-to-VMW', label: 'VPN Site-to-Site Configuration between Openstack portal and VMW' },
              ],
            },
            {
              type: 'category',
              label: 'VPN Connection Management',
              collapsed: true,
              items: [
                { type: 'doc', id: 'vpn-site-to-site/vpn-connection-management', label: 'VPN Connection Management' },
                { type: 'doc', id: 'vpn-site-to-site/create-a-vpn-connection', label: 'Create a VPN Connection' },
                { type: 'doc', id: 'vpn-site-to-site/edit-vpn-connection', label: 'Edit VPN Connection' },
                { type: 'doc', id: 'vpn-site-to-site/enable-disable-vpn-connection', label: 'Enable/Disable VPN Connection' },
                { type: 'doc', id: 'vpn-site-to-site/delete-vpn-connection', label: 'Delete VPN Connection' },
                { type: 'doc', id: 'vpn-site-to-site/create-customer-gateway', label: 'Create Customer gateway' },
                { type: 'doc', id: 'vpn-site-to-site/edit-customer-gateway', label: 'Edit Customer gateway' },
                { type: 'doc', id: 'vpn-site-to-site/delete-customer-gateway', label: 'Delete Customer gateway' },
                { type: 'doc', id: 'vpn-site-to-site/permission-access-guide', label: 'Service Authorization Management' },
                { type: 'doc', id: 'vpn-site-to-site/setting-up-alerts-via-the-cloud-guard-service-guide', label: 'Setting up alerts via the Cloud Guard service' },
                { type: 'doc', id: 'vpn-site-to-site/monitoring-service-through-monitoring-feature-guide', label: 'Service monitoring via the Monitoring feature' },
                { type: 'doc', id: 'vpn-site-to-site/monitoring-service-through-logging-feature-guide', label: 'Monitoring service through Logging feature' },
              ],
            },
            { type: 'doc', id: 'vpn-site-to-site/frequently-asked-question', label: 'FAQs' },
          ],
        },
        {
          type: 'category',
          label: 'Load Balancer',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'load-balancer/load-balancer', label: 'Overview' },
            { type: 'doc', id: 'load-balancer/initial-setup', label: 'Initial setup' },
            {
              type: 'category',
              label: 'Load Balancer (Tutorials)',
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: 'Manage Load Balancer',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'load-balancer/create-load-balancer', label: 'Create a Load Balancer' },
                    { type: 'doc', id: 'load-balancer/update-load-balancer', label: 'Update a Load Balancer' },
                    { type: 'doc', id: 'load-balancer/monitor-load-balancer', label: 'Monitor Load Balancer charts' },
                    { type: 'doc', id: 'load-balancer/add-external-member', label: 'Add external members' },
                    { type: 'doc', id: 'load-balancer/resize-load-balancer', label: 'Resize a Load Balancer' },
                    { type: 'doc', id: 'load-balancer/access-logs', label: 'Access logs' },
                    { type: 'doc', id: 'load-balancer/integrate-with-fmon', label: 'Integrate with FMON' },
                  ],
                },
                {
                  type: 'category',
                  label: 'Manage Listener',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'load-balancer/create-listener', label: 'Create a Listener' },
                    { type: 'doc', id: 'load-balancer/configure-timeout', label: 'Configure timeout' },
                    { type: 'doc', id: 'load-balancer/configure-l7-policy', label: 'Configure L7 policy' },
                    { type: 'doc', id: 'load-balancer/redirect-http-to-https', label: 'Redirect HTTP to HTTPS' },
                    { type: 'doc', id: 'load-balancer/redirect-prefix', label: 'Redirect prefix' },
                    { type: 'doc', id: 'load-balancer/enable-hsts', label: 'Enable HSTS' },
                    { type: 'doc', id: 'load-balancer/allow-ip-cidr', label: 'Configure Allow IP/CIDR' },
                    { type: 'doc', id: 'load-balancer/configure-sni', label: 'Configure SNI' },
                  ],
                },
                {
                  type: 'category',
                  label: 'Manage Server Pool',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'load-balancer/create-server-pool', label: 'Create a Server Pool' },
                    { type: 'doc', id: 'load-balancer/manage-pool-members', label: 'Add and remove pool members' },
                    { type: 'doc', id: 'load-balancer/configure-health-check', label: 'Configure health check' },
                  ],
                },
                {
                  type: 'category',
                  label: 'Manage SSL Certificate',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'load-balancer/import-ssl-certificate', label: 'Import SSL certificate' },
                    { type: 'doc', id: 'load-balancer/delete-ssl-certificate', label: 'Delete SSL certificate' },
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Classic Load Balancer (Tutorials)',
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: 'Manage Load Balancer',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'load-balancer/classic-create-load-balancer', label: 'Create a Classic Load Balancer' },
                    { type: 'doc', id: 'load-balancer/classic-add-instance', label: 'Add a VM to a Classic LB' },
                    { type: 'doc', id: 'load-balancer/classic-remove-instance', label: 'Remove a VM from a Classic LB' },
                    { type: 'doc', id: 'load-balancer/classic-update-load-balancer', label: 'Update Classic LB configuration' },
                    { type: 'doc', id: 'load-balancer/classic-delete-load-balancer', label: 'Delete a Classic Load Balancer' },
                  ],
                },
                {
                  type: 'category',
                  label: 'Manage SSL Certificate',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'load-balancer/classic-import-ssl-certificate', label: 'Import SSL certificate (Classic)' },
                    { type: 'doc', id: 'load-balancer/classic-view-ssl-certificate', label: 'View SSL certificate details (Classic)' },
                  ],
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Create VPC',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'create-vpc/initial-setup-en', label: 'Initial Setup' },
            { type: 'doc', id: 'create-vpc/rename-vpc-en', label: 'Rename VPC' },
            { type: 'doc', id: 'create-vpc/view-activity-en', label: 'Record Activity log and Recent task status' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'FPT Storage',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'FPT Object Storage',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-object-storage/initial-setup', label: 'Initial Setup' },
            {
              type: 'category',
              label: 'Using Object Storage on FPT Portal',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-object-storage/tutorials-using-object-storage-on-fpt-portal', label: 'Using Object Storage on FPT Portal' },
                { type: 'doc', id: 'fpt-object-storage/tutorials-bucket', label: 'Bucket' },
                { type: 'doc', id: 'fpt-object-storage/tutorials-object', label: 'Object' },
                { type: 'doc', id: 'fpt-object-storage/tutorials-permissions', label: 'Permissions' },
                { type: 'doc', id: 'fpt-object-storage/tutorials-bucket-config', label: 'Bucket Config' },
              ],
            },
            { type: 'doc', id: 'fpt-object-storage/tutorials-access-key-management', label: 'Access Key Management' },
            { type: 'doc', id: 'fpt-object-storage/tutorials-subuser-management', label: 'Subuser Management' },
            { type: 'doc', id: 'fpt-object-storage/tutorials-using-object-storage-on-s3-browser', label: 'Using Object Storage on S3 Browser' },
            { type: 'doc', id: 'fpt-object-storage/tutorials-integrate-fpt-object-storage-with-s3-client', label: 'Integrate FPT Object Storage with S3-Client' },
          ],
        },
        {
          type: 'category',
          label: 'File Storage - High Performance',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'file-storage-high-performance/initial-setup', label: 'Initial Setup' },
            {
              type: 'category',
              label: 'Vietnam Region',
              collapsed: true,
              items: [
                { type: 'doc', id: 'file-storage-high-performance/vietnam-region', label: 'Vietnam Region' },
                { type: 'doc', id: 'file-storage-high-performance/mountpoint-management', label: 'MountPoint Management' },
                { type: 'doc', id: 'file-storage-high-performance/vn-using-file-storage-high-performance-on-baremetal-gpu-server', label: 'Using File Storage – High Performance on Baremetal (GPU Server)' },
                { type: 'doc', id: 'file-storage-high-performance/using-file-storage-high-performance-on-kubernetes-k8s-cluster', label: 'Using File Storage – High Performance on Kubernetes (K8S Cluster)' },
              ],
            },
            {
              type: 'category',
              label: 'Japan Region',
              collapsed: true,
              items: [
                { type: 'doc', id: 'file-storage-high-performance/japan-region', label: 'Japan Region' },
                { type: 'doc', id: 'file-storage-high-performance/japan-using-file-storage-high-performance-on-baremetal-gpu-server', label: 'Using File Storage – High Performance on Baremetal (GPU Server)' },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'FPT Database Engine',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Managed – FPT Database Engine',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'managed-fpt-database-engine/fde-glossary', label: 'Glossary' },
            {
              type: 'category',
              label: 'Database Engine Version',
              collapsed: true,
              items: [
                { type: 'doc', id: 'managed-fpt-database-engine/database-engine-version', label: 'Database Engine Version' },
                { type: 'doc', id: 'managed-fpt-database-engine/version-policy', label: 'Version Policy' },
                { type: 'doc', id: 'managed-fpt-database-engine/Version-List', label: 'Supported Versions' },
              ],
            },
            { type: 'doc', id: 'managed-fpt-database-engine/deployment-model', label: 'Deployment Models' },
            { type: 'doc', id: 'managed-fpt-database-engine/network-connectivity', label: 'Networking and Connectivity' },
            { type: 'doc', id: 'managed-fpt-database-engine/maintenance', label: 'Maintenance' },
            { type: 'doc', id: 'managed-fpt-database-engine/Initial-setup', label: 'Initial Setup Requirements' },
            { type: 'doc', id: 'managed-fpt-database-engine/register-account', label: 'Register an account' },
            { type: 'doc', id: 'managed-fpt-database-engine/access-console', label: 'Accessing FPT Console Portal' },
            {
              type: 'category',
              label: 'FPT Database Engine Right Management',
              collapsed: true,
              items: [
                { type: 'doc', id: 'managed-fpt-database-engine/iam', label: 'FPT Database Engine Right Management' },
                { type: 'doc', id: 'managed-fpt-database-engine/role', label: 'Role Management' },
                { type: 'doc', id: 'managed-fpt-database-engine/user-group', label: 'User Group Management' },
              ],
            },
            { type: 'doc', id: 'managed-fpt-database-engine/subnet', label: 'Subnet Management' },
            {
              type: 'category',
              label: 'FPT Database Engine Service Management',
              collapsed: true,
              items: [
                { type: 'doc', id: 'managed-fpt-database-engine/db-engine-service', label: 'FPT Database Engine Service Management' },
                { type: 'doc', id: 'managed-fpt-database-engine/active-db-service', label: 'Activate FPT Database Engine Service' },
                { type: 'doc', id: 'managed-fpt-database-engine/deactive-db-service', label: 'Deactivate FPT Database Engine Service' },
              ],
            },
            {
              type: 'category',
              label: 'Database Provisioning and Operation',
              collapsed: true,
              items: [
                { type: 'doc', id: 'managed-fpt-database-engine/db-manage-operate', label: 'Database Provisioning and Operation' },
                { type: 'doc', id: 'managed-fpt-database-engine/view-db-list', label: 'View Database List' },
                { type: 'doc', id: 'managed-fpt-database-engine/create-db', label: 'Provision Database' },
                { type: 'doc', id: 'managed-fpt-database-engine/db-view-detail', label: 'View database cluster information' },
                { type: 'doc', id: 'managed-fpt-database-engine/db-connect', label: 'Connect to the Database' },
                { type: 'doc', id: 'managed-fpt-database-engine/db-operation', label: 'Database Operations' },
                { type: 'doc', id: 'managed-fpt-database-engine/upgrade-version', label: 'Upgrade Database Engine Version' },
              ],
            },
            {
              type: 'category',
              label: 'Backup & Restore',
              collapsed: true,
              items: [
                { type: 'doc', id: 'managed-fpt-database-engine/backup-restore', label: 'Backup & Restore' },
                { type: 'doc', id: 'managed-fpt-database-engine/backup-mgmt', label: 'Backup Service Management' },
                { type: 'doc', id: 'managed-fpt-database-engine/backup-job-mgmt', label: 'Backup Job Management' },
                { type: 'doc', id: 'managed-fpt-database-engine/on-off-pitr', label: 'Enabling/Disabling PITR' },
                { type: 'doc', id: 'managed-fpt-database-engine/restore-db', label: 'Database Recovery' },
                { type: 'doc', id: 'managed-fpt-database-engine/push-s3', label: 'Push backup to S3' },
              ],
            },
            { type: 'doc', id: 'managed-fpt-database-engine/resource', label: 'Database Resource Management' },
            { type: 'doc', id: 'managed-fpt-database-engine/param', label: 'Parameter Management' },
            { type: 'doc', id: 'managed-fpt-database-engine/kafka-user', label: 'Apache Kafka - User Management' },
            { type: 'doc', id: 'managed-fpt-database-engine/db-proxy', label: 'DB Proxy' },
            { type: 'doc', id: 'managed-fpt-database-engine/vertical-scaling', label: 'Vertical Scaling' },
            { type: 'doc', id: 'managed-fpt-database-engine/maintenance-window', label: 'Maintenance Window' },
            { type: 'doc', id: 'managed-fpt-database-engine/notification', label: 'Notification' },
            { type: 'doc', id: 'managed-fpt-database-engine/monitoring', label: 'Monitoring' },
            { type: 'doc', id: 'managed-fpt-database-engine/logs', label: 'Event Logs' },
            {
              type: 'category',
              label: 'Reporting',
              collapsed: true,
              items: [
                { type: 'doc', id: 'managed-fpt-database-engine/report', label: 'Reporting' },
                { type: 'doc', id: 'managed-fpt-database-engine/report-export', label: 'Manual Report Export' },
                { type: 'doc', id: 'managed-fpt-database-engine/report-schedule', label: 'Report Schedule' },
              ],
            },
            { type: 'doc', id: 'managed-fpt-database-engine/benchmark-sysbench', label: 'Sysbench Benchmark Results' },
            { type: 'doc', id: 'managed-fpt-database-engine/mysql-troubleshooting', label: 'MySQL' },
            { type: 'doc', id: 'managed-fpt-database-engine/clickhouse-use-ha', label: 'ClickHouse - High Availability (HA)' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'FPT Integration',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'FPT Message Bus',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-message-bus/initial-setup', label: 'Initial Setup' },
            { type: 'doc', id: 'fpt-message-bus/Quick-Starts', label: 'Quick Starts' },
            {
              type: 'category',
              label: 'Manage Queues',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-message-bus/Manage-Queues', label: 'Manage Queues' },
                { type: 'doc', id: 'fpt-message-bus/Create-queues', label: 'Create Queues' },
                { type: 'doc', id: 'fpt-message-bus/View-queues', label: 'View Queues' },
                { type: 'doc', id: 'fpt-message-bus/Send-Receive-messages-in-queues', label: 'Send & Receive Messages in Queues' },
                { type: 'doc', id: 'fpt-message-bus/Delete-queues', label: 'Delete Queues' },
              ],
            },
            {
              type: 'category',
              label: 'Manage Topics',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-message-bus/Manage-topics', label: 'Manage Topics' },
                { type: 'doc', id: 'fpt-message-bus/Create-topics', label: 'Create Topics' },
                { type: 'doc', id: 'fpt-message-bus/Create-Subscriptions', label: 'Create Subscriptions' },
                { type: 'doc', id: 'fpt-message-bus/Edit-topics', label: 'Edit Topics' },
                { type: 'doc', id: 'fpt-message-bus/Send-Receive-messages-in-topics', label: 'Send & Receive Messages in Topics' },
                { type: 'doc', id: 'fpt-message-bus/Delete-topics', label: 'Delete Topics' },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'FPT Kafka',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-kafka/initial-setup', label: 'Initial Setup' },
            { type: 'doc', id: 'fpt-kafka/quick-starts', label: 'Quick Starts' },
            {
              type: 'category',
              label: 'Manage Topics',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-kafka/manage-topics', label: 'Manage Topics' },
                { type: 'doc', id: 'fpt-kafka/create-topics', label: 'Create Topics' },
                { type: 'doc', id: 'fpt-kafka/view-topics', label: 'View Topics' },
                { type: 'doc', id: 'fpt-kafka/edit-topics', label: 'Edit Topics' },
                { type: 'doc', id: 'fpt-kafka/delete-topics', label: 'Delete Topics' },
              ],
            },
            {
              type: 'category',
              label: 'Manage Credentials',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-kafka/manage-credentials', label: 'Manage Credentials' },
                { type: 'doc', id: 'fpt-kafka/create-credentials', label: 'Create Credentials' },
                { type: 'doc', id: 'fpt-kafka/edit-credentials', label: 'Edit Credentials' },
                { type: 'doc', id: 'fpt-kafka/delete-credentials', label: 'Delete Credentials' },
              ],
            },
            {
              type: 'category',
              label: 'Manage ACLs',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-kafka/manage-acls', label: 'Manage ACLs' },
                { type: 'doc', id: 'fpt-kafka/create-acls', label: 'Create ACLs' },
                { type: 'doc', id: 'fpt-kafka/delete-acls', label: 'Delete ACLs' },
              ],
            },
            {
              type: 'category',
              label: 'Manage Consumer Groups',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-kafka/manage-consumer-groups', label: 'Manage Consumer Groups' },
                { type: 'doc', id: 'fpt-kafka/create-consumer-groups', label: 'Create Consumer Groups' },
                { type: 'doc', id: 'fpt-kafka/view-consumer-groups', label: 'View Consumer Groups' },
                { type: 'doc', id: 'fpt-kafka/delete-consumer-groups', label: 'Delete Consumer Groups' },
              ],
            },
            { type: 'doc', id: 'fpt-kafka/demo', label: 'Demo' },
          ],
        },
        {
          type: 'category',
          label: 'FPT API Management',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-api-management/initial-setup', label: 'Initial Setup' },
            { type: 'doc', id: 'fpt-api-management/quick-starts', label: 'Quick Starts' },
            { type: 'doc', id: 'fpt-api-management/registering-on-fpt-portal', label: 'Registering for FPT API Management service on FPT Portal' },
            {
              type: 'category',
              label: 'Declaring information in ApiManager Application',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-api-management/declaring-information', label: 'Declaring information in ApiManager Application' },
                { type: 'doc', id: 'fpt-api-management/manage-rest-apis', label: 'Managing REST APIs' },
                { type: 'doc', id: 'fpt-api-management/managing-products', label: 'Managing Products' },
                { type: 'doc', id: 'fpt-api-management/managing-sites', label: 'Managing Sites' },
                { type: 'doc', id: 'fpt-api-management/managing-consumers', label: 'Managing Consumers' },
              ],
            },
            { type: 'doc', id: 'fpt-api-management/analytics', label: 'Analytics' },
            { type: 'doc', id: 'fpt-api-management/consumer-api-usage-guide', label: 'Consumer API Usage Guide' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'FPT DevSecOps Services',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'FPT Key Vault',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-key-vault/Initial-Setup', label: 'Initial Setup' },
            { type: 'doc', id: 'fpt-key-vault/Create-Vault-Instance', label: 'Create Vault Instance' },
            {
              type: 'category',
              label: 'Secret Engine Management',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-key-vault/Secret-Engine-Management', label: 'Secret Engine Management' },
                { type: 'doc', id: 'fpt-key-vault/Create-Secret-Engine', label: 'Create Secret Engine' },
                { type: 'doc', id: 'fpt-key-vault/Delete-Secret-Engine', label: 'Delete Secret Engine' },
              ],
            },
            {
              type: 'category',
              label: 'Secret Management',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-key-vault/Secret-management', label: 'Secret Management' },
                { type: 'doc', id: 'fpt-key-vault/Create-Secret-in-Secret-Engine', label: 'Create Secret in Secret Engine' },
                { type: 'doc', id: 'fpt-key-vault/View-and-Update-Secret-information', label: 'View and Update Secret Informations' },
                { type: 'doc', id: 'fpt-key-vault/Delete-Secret', label: 'Delete Secret' },
              ],
            },
            {
              type: 'category',
              label: 'Policy Management',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-key-vault/Policy-management', label: 'Policy Management' },
                { type: 'doc', id: 'fpt-key-vault/Create-Policy', label: 'Create Policy' },
                { type: 'doc', id: 'fpt-key-vault/Delete-Policy', label: 'Delete Policy' },
              ],
            },
            {
              type: 'category',
              label: 'Auth Method Management',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-key-vault/Auth-Method-Management', label: 'Auth Method Management' },
                { type: 'doc', id: 'fpt-key-vault/Create-Auth-Method', label: 'Create Auth Method' },
                { type: 'doc', id: 'fpt-key-vault/Create-Role', label: 'Create Role' },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'FPT ArgoCD',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-argocd/initial-setup', label: 'Initial Setup' },
            { type: 'doc', id: 'fpt-argocd/check-service-package-info', label: 'Check Service Package Info' },
            { type: 'doc', id: 'fpt-argocd/create-fpt-argocd', label: 'Create a new FPT ArgoCD' },
            { type: 'doc', id: 'fpt-argocd/view-argocd-detail', label: 'View ArgoCD detail information' },
            { type: 'doc', id: 'fpt-argocd/add-cluster-to-argocd', label: 'Add cluster to ArgoCD' },
            {
              type: 'category',
              label: 'Configure ArgoCD',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-argocd/configure-image-updater', label: 'Configure Image Updater' },
                { type: 'doc', id: 'fpt-argocd/enable-disable-images-updater', label: 'Enable/disable Images Updater' },
                { type: 'doc', id: 'fpt-argocd/configure-log-level', label: 'Configure Log Level' },
                { type: 'doc', id: 'fpt-argocd/manage-secrets', label: 'Manage Secrets' },
                { type: 'doc', id: 'fpt-argocd/manage-registry-secrets', label: 'Manage Registry Secrets' },
                { type: 'doc', id: 'fpt-argocd/manage-container-registry', label: 'Manage Container Registry' },
              ],
            },
            {
              type: 'category',
              label: 'Webhook',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-argocd/configure-webhook', label: 'Configure Webhook' },
                { type: 'doc', id: 'fpt-argocd/add-webhook-secret', label: 'Add a Webhook Secret' },
                { type: 'doc', id: 'fpt-argocd/edit-webhook-secret', label: 'Edit a Webhook Secret' },
                { type: 'doc', id: 'fpt-argocd/delete-webhook-secret', label: 'Delete a Webhook Secret' },
              ],
            },
            { type: 'doc', id: 'fpt-argocd/configure-build-options-kustomize', label: 'Configure Build Options for Kustomize' },
            { type: 'doc', id: 'fpt-argocd/configure-timereconcile', label: 'Configure TimeReconcile' },
            { type: 'doc', id: 'fpt-argocd/configure-rbac', label: 'Configure RBAC Policy' },
            { type: 'doc', id: 'fpt-argocd/configure-whitelist-ip', label: 'Configure Whitelist IP' },
            { type: 'doc', id: 'fpt-argocd/upgrade-service-package', label: 'Upgrade Service Package' },
            { type: 'doc', id: 'fpt-argocd/upgrade-version', label: 'Upgrade ArgoCD Version' },
            {
              type: 'category',
              label: 'Manage Accounts',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-argocd/manage-accounts', label: 'Manage Accounts' },
                { type: 'doc', id: 'fpt-argocd/create-account', label: 'Create a new Account' },
                { type: 'doc', id: 'fpt-argocd/edit-capabilities', label: 'Edit Capabilities' },
                { type: 'doc', id: 'fpt-argocd/change-password', label: 'Change Password' },
                { type: 'doc', id: 'fpt-argocd/enable-disable-account', label: 'Enable/disable Account' },
                { type: 'doc', id: 'fpt-argocd/manage-admin-account', label: 'Manage Admin Account' },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'FPT Monitoring',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Incident Management',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'incident-management/initial-setup', label: 'Initial Setup' },
            {
              type: 'category',
              label: 'Configure Integrations',
              collapsed: true,
              items: [
                { type: 'doc', id: 'incident-management/configure-integrations', label: 'Configure Integrations' },
                { type: 'doc', id: 'incident-management/incoming-webhook', label: 'Incoming Webhook' },
                { type: 'doc', id: 'incident-management/outgoing-webhook', label: 'Outgoing Webhook' },
                { type: 'doc', id: 'incident-management/atlassian-jira', label: 'Atlassian Jira' },
                { type: 'doc', id: 'incident-management/microsoft-teams', label: 'Microsoft Teams' },
                { type: 'doc', id: 'incident-management/slack', label: 'Slack' },
                { type: 'doc', id: 'incident-management/telegram', label: 'Telegram' },
                { type: 'doc', id: 'incident-management/grafana-webhook', label: 'Grafana Webhook' },
              ],
            },
            {
              type: 'category',
              label: 'Configure Incident Settings',
              collapsed: true,
              items: [
                { type: 'doc', id: 'incident-management/configure-incident-settings', label: 'Configure Incident Settings' },
                { type: 'doc', id: 'incident-management/incident-label', label: 'Incident Label' },
                { type: 'doc', id: 'incident-management/incident-severity', label: 'Incident Severity' },
                { type: 'doc', id: 'incident-management/incident-status', label: 'Incident Status' },
              ],
            },
            { type: 'doc', id: 'incident-management/create-incident', label: 'Create an Incident' },
            { type: 'doc', id: 'incident-management/declare-incident', label: 'Declare an Incident' },
            { type: 'doc', id: 'incident-management/create-incident-via-webhook', label: 'Create Incident via Webhook' },
            {
              type: 'category',
              label: 'Manage Incidents',
              collapsed: true,
              items: [
                { type: 'doc', id: 'incident-management/manage-incidents', label: 'Manage Incidents' },
                { type: 'doc', id: 'incident-management/view-incident-detail', label: 'View Incident Detail' },
                { type: 'doc', id: 'incident-management/post-incident-activity', label: 'Post Incident Activity' },
                { type: 'doc', id: 'incident-management/copy-activities-as-markdown', label: 'Copy Activities as Markdown' },
                { type: 'doc', id: 'incident-management/change-the-incident-status', label: 'Change the Incident Status' },
                { type: 'doc', id: 'incident-management/change-the-incident-severity', label: 'Change the Incident Severity' },
                { type: 'doc', id: 'incident-management/filter-incidents', label: 'Filter Incidents' },
              ],
            },
            { type: 'doc', id: 'incident-management/incident-data-visualization', label: 'Incident Data Visualization' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'FPT Security',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'IAM',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'iam/initial-setup', label: 'Initial Setup' },
            {
              type: 'category',
              label: 'Role Management',
              collapsed: true,
              items: [
                { type: 'doc', id: 'iam/role-management', label: 'Role Management' },
                { type: 'doc', id: 'iam/role-overview', label: 'Overview' },
                { type: 'doc', id: 'iam/view-role-list', label: 'View role list' },
                { type: 'doc', id: 'iam/create-role', label: 'Create a role and assign permissions' },
                { type: 'doc', id: 'iam/view-role-detail', label: 'View role details' },
                { type: 'doc', id: 'iam/edit-role-and-permissions', label: 'Edit roles and permissions' },
                { type: 'doc', id: 'iam/delete-role', label: 'Delete role' },
              ],
            },
            {
              type: 'category',
              label: 'Manage User Groups',
              collapsed: true,
              items: [
                { type: 'doc', id: 'iam/manage-user-groups', label: 'Manage User Groups' },
                { type: 'doc', id: 'iam/overview-user-group', label: 'Overview' },
                { type: 'doc', id: 'iam/create-user-group', label: 'Create a new User Group' },
                { type: 'doc', id: 'iam/view-list-user-group', label: 'View list User group' },
                { type: 'doc', id: 'iam/view-detail-user-group', label: 'View detail User group' },
                { type: 'doc', id: 'iam/edit-user-group', label: 'Edit User group' },
                { type: 'doc', id: 'iam/delete-user-group', label: 'Delete user group' },
              ],
            },
            {
              type: 'category',
              label: 'Manage IAM Users',
              collapsed: true,
              items: [
                { type: 'doc', id: 'iam/overview-iam-user', label: 'Overview' },
                { type: 'doc', id: 'iam/invite-iam-user', label: 'Invite new IAM users' },
                { type: 'doc', id: 'iam/create-account-access-vpc', label: 'Create an account and access the invited VPC' },
                { type: 'doc', id: 'iam/change-password', label: 'Change password' },
                { type: 'doc', id: 'iam/configure-2fa', label: 'Configure 2FA' },
              ],
            },
            {
              type: 'category',
              label: 'IP Access',
              collapsed: true,
              items: [
                { type: 'doc', id: 'iam/ip-access', label: 'IP Access' },
                { type: 'doc', id: 'iam/overview-ip-access', label: 'Overview' },
                { type: 'doc', id: 'iam/create-ip-access', label: 'Create a new IP access record' },
                { type: 'doc', id: 'iam/delete-ip-access', label: 'Delete an IP access record' },
                { type: 'doc', id: 'iam/ip-access-activity-log', label: 'Check IP access activity logs' },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'FPT Cloud WAF',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-cloud-waf/Initial Setup', label: 'Initial Setup' },
            { type: 'doc', id: 'fpt-cloud-waf/create-a-new-waf-server', label: 'Create a new WAF server' },
            { type: 'doc', id: 'fpt-cloud-waf/log-in-to-waf-dashboard', label: 'Log in to WAF Dashboard' },
            { type: 'doc', id: 'fpt-cloud-waf/configure-waf-server-connection', label: 'Configure WAF server connection' },
            { type: 'doc', id: 'fpt-cloud-waf/tutorials-create-a-new-waf-server', label: 'Create a new WAF server' },
            { type: 'doc', id: 'fpt-cloud-waf/update-information-of-the-WAF-server', label: 'Update information of the WAF server' },
            { type: 'doc', id: 'fpt-cloud-waf/delete-waf-server', label: 'Delete WAF server' },
            {
              type: 'category',
              label: 'Manage WAF server with WAF Dashboard',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-cloud-waf/manage-waf-server-with-waf-dashboard', label: 'Manage WAF server with WAF Dashboard' },
                { type: 'doc', id: 'fpt-cloud-waf/tutorials-log-in-to-waf-dashboard', label: 'Log in to WAF dashboard' },
                { type: 'doc', id: 'fpt-cloud-waf/monitor-waf-server-with-dashboard-overview', label: 'Monitor WAF server with Dashboard Overview' },
                {
                  type: 'category',
                  label: 'Proxy Host',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'fpt-cloud-waf/manage-proxy-host', label: 'Manage Proxy Host' },
                    { type: 'doc', id: 'fpt-cloud-waf/create-proxy-host', label: 'Create a Proxy Host' },
                    { type: 'doc', id: 'fpt-cloud-waf/view-proxy-host-detail', label: 'View Proxy Host detail' },
                    { type: 'doc', id: 'fpt-cloud-waf/update-proxy-host', label: 'Update Proxy Host' },
                    { type: 'doc', id: 'fpt-cloud-waf/enable-disable-proxy-host', label: 'Enable/disable Proxy Host' },
                    { type: 'doc', id: 'fpt-cloud-waf/delete-proxy-host', label: 'Delete Proxy Host' },
                  ],
                },
                { type: 'doc', id: 'fpt-cloud-waf/manage-redirection-host', label: 'Manage Redirection Host' },
                { type: 'doc', id: 'fpt-cloud-waf/manage-stream-host', label: 'Manage Stream Host' },
                { type: 'doc', id: 'fpt-cloud-waf/manage-404-host', label: 'Manage 404 Host' },
                { type: 'doc', id: 'fpt-cloud-waf/manage-access-list', label: 'Manage Access List' },
                { type: 'doc', id: 'fpt-cloud-waf/manage-ssl-certificate', label: 'Manage SSL Certificates' },
                { type: 'doc', id: 'fpt-cloud-waf/manage-security-rule-set', label: 'Manage Security Rule Sets' },
              ],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Billing',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Cost Explorer',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'cost-explorer/View-dashboards-and-specific-costs-by-service', label: 'View dashboards and specific costs by service' },
            { type: 'doc', id: 'cost-explorer/customer-filter', label: 'Customize filters to see costs by specific time or resource group' },
            { type: 'doc', id: 'cost-explorer/questions-2', label: 'I want to see the Cost Explorer of some Instances or Security Groups, but the Customize Filter does not allow me to select?' },
          ],
        },
        {
          type: 'category',
          label: 'Budget Alert',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'budget-alert/initiating-a-budget-alert', label: 'Initiating a Budget Alert' },
            { type: 'doc', id: 'budget-alert/view-cost-information', label: 'View cost information and warning history' },
            { type: 'doc', id: 'budget-alert/pause-budget-alert', label: 'Pause 1 Budget Alert alerts' },
            { type: 'doc', id: 'budget-alert/delete-budget-alert', label: 'Delete Budget Alert' },
            { type: 'doc', id: 'budget-alert/setting-budget-alert', label: 'Prevent the creation of new Compute/Network resources when the budget threshold is reached' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Support',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Trellix Customer Guide',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'trellix-customer-guide/Access the administration interface', label: 'Access the administration interface' },
            { type: 'doc', id: 'trellix-customer-guide/client-task-mapping', label: 'Managing Client Tasks on Servers (Client Tasks)' },
            { type: 'doc', id: 'trellix-customer-guide/report-guide', label: 'Reports' },
            { type: 'doc', id: 'trellix-customer-guide/Viewing Logs', label: 'Viewing Logs' },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'FPT AI Factory',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'AI Factory Billing',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'ai-factory-billing/ai-factory-billing', label: 'AI Factory Billing' },
            { type: 'doc', id: 'ai-factory-billing/overview', label: 'Overview' },
            { type: 'doc', id: 'ai-factory-billing/quick-start', label: 'Quick start' },
            { type: 'doc', id: 'ai-factory-billing/balance', label: 'Balance' },
            { type: 'doc', id: 'ai-factory-billing/low-balance-threshold-alert', label: 'Low balance alert' },
            { type: 'doc', id: 'ai-factory-billing/credit-history', label: 'Credit history' },
            { type: 'doc', id: 'ai-factory-billing/voucher-list', label: 'Voucher list' },
            { type: 'doc', id: 'ai-factory-billing/payment-methods', label: 'Payment methods' },
            { type: 'doc', id: 'ai-factory-billing/billing-calculation', label: 'Billing calculation' },
            { type: 'doc', id: 'ai-factory-billing/gpu-container-billing', label: 'GPU Container billing' },
            { type: 'doc', id: 'ai-factory-billing/model-hub-billing', label: 'Model Hub billing' },
            { type: 'doc', id: 'ai-factory-billing/model-finetuning-billing', label: 'Model Fine-Tuning billing' },
            { type: 'doc', id: 'ai-factory-billing/modas-billing', label: 'MoDaS billing' },
            { type: 'doc', id: 'ai-factory-billing/add-credits', label: 'Add credits' },
            { type: 'doc', id: 'ai-factory-billing/redeem-voucher', label: 'Redeem voucher' },
            { type: 'doc', id: 'ai-factory-billing/payment-invoice', label: 'Payment Invoice' },
            { type: 'doc', id: 'ai-factory-billing/billing-plan', label: 'Billing Plan' },
            { type: 'doc', id: 'ai-factory-billing/billing-faq', label: 'Billing FAQ' }
          ],
        },
        {
          type: 'category',
          label: 'AI Notebook',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'ai-notebook/ai-notebook', label: 'AI Notebook' },
            { type: 'doc', id: 'ai-notebook/about-ai-notebooks', label: 'About AI Notebooks' },
            { type: 'doc', id: 'ai-notebook/quick-start', label: 'Quick start' },
            { type: 'doc', id: 'ai-notebook/launch-ai-notebook', label: 'Launch AI Notebook' },
            { type: 'doc', id: 'ai-notebook/create-notebook', label: 'Create a notebook' },
            { type: 'doc', id: 'ai-notebook/connect-switch-kernel', label: 'Connect and switch kernel' },
            { type: 'doc', id: 'ai-notebook/shut-down-kernel', label: 'Shut down kernel' },
            { type: 'doc', id: 'ai-notebook/faq', label: 'FAQ' }
          ],
        },
        {
          type: 'category',
          label: 'AI Marketplace',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'ai_marketplace/ai_marketplace', label: 'AI Marketplace' },
            { type: 'doc', id: 'ai_marketplace/overview', label: 'Overview' },
            { type: 'doc', id: 'ai_marketplace/quick-start', label: 'Quick start' },
            { type: 'doc', id: 'ai_marketplace/home-page', label: 'Home page' },
            { type: 'doc', id: 'ai_marketplace/product-information', label: 'Product information' },
            { type: 'doc', id: 'ai_marketplace/playground', label: 'Playground' },
            { type: 'doc', id: 'ai_marketplace/fine-tune-with-lora', label: 'Fine-tune with LoRA' },
            { type: 'doc', id: 'ai_marketplace/deployment-lora-inference', label: 'Deploy LoRA inference' },
            { type: 'doc', id: 'ai_marketplace/my-account', label: 'My account' },
            { type: 'doc', id: 'ai_marketplace/balance', label: 'Balance' },
            { type: 'doc', id: 'ai_marketplace/billing', label: 'Billing' },
            { type: 'doc', id: 'ai_marketplace/contact-us', label: 'Contact us' },
            { type: 'doc', id: 'ai_marketplace/how-to-create-an-api-key', label: 'Create an API key' },
            { type: 'doc', id: 'ai_marketplace/api-integration', label: 'API integration' },
            { type: 'doc', id: 'ai_marketplace/deprecated-models', label: 'Deprecated models' },
            { type: 'doc', id: 'ai_marketplace/FAQ', label: 'FAQ' }
          ],
        },
        {
          type: 'category',
          label: 'Data Hub',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'data-hub/data-hub', label: 'Data Hub' },
            { type: 'doc', id: 'data-hub/initial-setup', label: 'Initial setup' },
            { type: 'doc', id: 'data-hub/create-connection', label: 'Create a connection' },
            { type: 'doc', id: 'data-hub/generate-dataset', label: 'Generate a dataset' }
          ],
        },
        {
          type: 'category',
          label: 'GPU Container',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'gpu-container/gpu-container', label: 'GPU Container' },
            { type: 'doc', id: 'gpu-container/about-gpu-container', label: 'About Gpu Container' },
            { type: 'doc', id: 'gpu-container/quick-start', label: 'Sign Up for an...' },
            { type: 'doc', id: 'gpu-container/create-new-container', label: 'GPU Container' },
            { type: 'doc', id: 'gpu-container/create-via-gui', label: 'Create Via Gui' },
            { type: 'doc', id: 'gpu-container/import-config', label: 'Import Config' },
            { type: 'doc', id: 'gpu-container/export-config', label: 'Export Config' },
            { type: 'doc', id: 'gpu-container/connect-container', label: 'Connect Container' },
            { type: 'doc', id: 'gpu-container/manage-container', label: 'Manage Container' },
            { type: 'doc', id: 'gpu-container/logs-and-monitoring', label: 'Logs And Monitoring' },
            { type: 'doc', id: 'gpu-container/templates', label: 'Templates' },
            { type: 'doc', id: 'gpu-container/storage', label: 'Storage' },
            { type: 'doc', id: 'gpu-container/billing-overview', label: 'Billing Overview' },
            { type: 'doc', id: 'gpu-container/payment-model', label: 'Payment Model' },
            { type: 'doc', id: 'gpu-container/pricing', label: 'Pricing' },
            { type: 'doc', id: 'gpu-container/add-credit', label: 'Add Credit' },
            { type: 'doc', id: 'gpu-container/jupyter-notebook-tutorials', label: 'Jupyter Notebook Tutorials' },
            { type: 'doc', id: 'gpu-container/vllm-use-cases', label: 'GPU Container' },
            { type: 'doc', id: 'gpu-container/vllm-use-case', label: 'Vllm Use Case' },
            { type: 'doc', id: 'gpu-container/vllm-use-cases-gpt-oss', label: 'Vllm Use Cases Gpt...' },
            { type: 'doc', id: 'gpu-container/ollama-use-cases', label: 'Ollama Use Cases' },
            { type: 'doc', id: 'gpu-container/code-server-use-cases', label: 'Load fine-tuned model and...' },
            { type: 'doc', id: 'gpu-container/ubuntu-use-cases', label: 'Ubuntu Use Cases' },
            { type: 'doc', id: 'gpu-container/Action', label: 'Action' },
            { type: 'doc', id: 'gpu-container/billing', label: 'Billing' }
          ],
        },
        {
          type: 'category',
          label: 'GPU Virtual Machine',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'gpu-virtual-machine-en/gpu-virtual-machine-en', label: 'GPU Virtual Machine' },
            { type: 'doc', id: 'gpu-virtual-machine-en/overview', label: 'Overview' },
            { type: 'doc', id: 'gpu-virtual-machine-en/quick-start', label: 'Quick Start' },
            { type: 'doc', id: 'gpu-virtual-machine-en/fpt_images', label: 'Fpt_Images' },
            { type: 'doc', id: 'gpu-virtual-machine-en/custom-images', label: 'Custom Images' },
            { type: 'doc', id: 'gpu-virtual-machine-en/block-storage', label: 'Block Storage' },
            { type: 'doc', id: 'gpu-virtual-machine-en/create-a-subnet', label: 'Create A Subnet' },
            { type: 'doc', id: 'gpu-virtual-machine-en/create-a-gpu-vm', label: 'Create A Gpu Vm' },
            { type: 'doc', id: 'gpu-virtual-machine-en/floating-ip', label: 'Floating Ip' },
            { type: 'doc', id: 'gpu-virtual-machine-en/create-a-security-group', label: 'Create A Security Group' },
            { type: 'doc', id: 'gpu-virtual-machine-en/access-to-servers', label: 'Access To Servers' },
            { type: 'doc', id: 'gpu-virtual-machine-en/manage-gpu-vms', label: 'Manage Gpu Vms' },
            { type: 'doc', id: 'gpu-virtual-machine-en/monitor-gpu-vms', label: 'Monitor Gpu Vms' },
            { type: 'doc', id: 'gpu-virtual-machine-en/create-a-snapshot', label: 'Create A Snapshot' },
            { type: 'doc', id: 'gpu-virtual-machine-en/pfsense-network-gateway', label: 'Pfsense Network Gateway' },
            { type: 'doc', id: 'gpu-virtual-machine-en/faq', label: 'Faq' }
          ],
        },
        {
          type: 'category',
          label: 'Model Fine-Tuning',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'model-fine-tuning/model-fine-tuning', label: 'Model Fine-Tuning' },
            { type: 'doc', id: 'model-fine-tuning/overview', label: 'Model Fine-Tuning' },
            { type: 'doc', id: 'model-fine-tuning/what-is-model-fine-tuning', label: 'What Is Model Fine...' },
            { type: 'doc', id: 'model-fine-tuning/when-to-use-model-fine-tuning', label: 'When To Use Model...' },
            { type: 'doc', id: 'model-fine-tuning/quick-start', label: 'Model Fine-Tuning' },
            { type: 'doc', id: 'model-fine-tuning/sign-up-for-an-account', label: 'Sign Up For An...' },
            { type: 'doc', id: 'model-fine-tuning/step-by-step', label: 'Step By Step' },
            { type: 'doc', id: 'model-fine-tuning/how-to-create-pipeline', label: 'How To Create Pipeline' },
            { type: 'doc', id: 'model-fine-tuning/select-base-model', label: 'Select Base Model' },
            { type: 'doc', id: 'model-fine-tuning/select-trainer', label: 'Select Trainer' },
            { type: 'doc', id: 'model-fine-tuning/select-volume', label: 'Select Volume' },
            { type: 'doc', id: 'model-fine-tuning/select-dataset-format', label: 'Select Dataset Format' },
            { type: 'doc', id: 'model-fine-tuning/select-dataset', label: 'Select Dataset' },
            { type: 'doc', id: 'model-fine-tuning/set-up-hyperparameters', label: 'Set Up Hyperparameters' },
            { type: 'doc', id: 'model-fine-tuning/set-up-infrastructure', label: 'Set Up Infrastructure' },
            { type: 'doc', id: 'model-fine-tuning/finish', label: 'Finish' },
            { type: 'doc', id: 'model-fine-tuning/how-to-manage-pipeline', label: 'How To Manage Pipeline' },
            { type: 'doc', id: 'model-fine-tuning/start-pipeline', label: 'Start Pipeline' },
            { type: 'doc', id: 'model-fine-tuning/cancel-pipeline', label: 'Cancel Pipeline' },
            { type: 'doc', id: 'model-fine-tuning/edit-pipeline', label: 'Edit Pipeline' },
            { type: 'doc', id: 'model-fine-tuning/delete-pipeline', label: 'Delete Pipeline' },
            { type: 'doc', id: 'model-fine-tuning/execution-history', label: 'Execution History' },
            { type: 'doc', id: 'model-fine-tuning/execution-details', label: 'Execution Details' },
            { type: 'doc', id: 'model-fine-tuning/how-to-monitor-and-evaluate', label: 'How To Monitor And...' },
            { type: 'doc', id: 'model-fine-tuning/model-metrics', label: 'Model Metrics' },
            { type: 'doc', id: 'model-fine-tuning/system-metrics', label: 'System Metrics' },
            { type: 'doc', id: 'model-fine-tuning/logs', label: 'Logs' },
            { type: 'doc', id: 'model-fine-tuning/fine-tune-the-gemma-3-27B-instruct-model-for-financial-tasks', label: 'Fine Tune The Gemma...' },
            { type: 'doc', id: 'model-fine-tuning/jaist-accelerates-japanese-llm-development-with-fpt-ai-factory', label: 'Model Fine-Tuning' },
            { type: 'doc', id: 'model-fine-tuning/summary', label: 'Summary' },
            { type: 'doc', id: 'model-fine-tuning/about-jaist', label: 'About Jaist' },
            { type: 'doc', id: 'model-fine-tuning/challenges', label: 'Challenges' },
            { type: 'doc', id: 'model-fine-tuning/fpt-ai-factory-solution', label: 'Fpt Ai Factory Solution' },
            { type: 'doc', id: 'model-fine-tuning/business-impact', label: 'Business Impact' },
            { type: 'doc', id: 'model-fine-tuning/faq', label: 'Faq' }
          ],
        },
        {
          type: 'category',
          label: 'Model Hub',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'model-hub/model-hub', label: 'Model Hub' },
            { type: 'doc', id: 'model-hub/overview', label: 'Overview' },
            { type: 'doc', id: 'model-hub/what-is-model-hub', label: 'What Is Model Hub' },
            { type: 'doc', id: 'model-hub/how-does-it-work', label: 'How does it work' },
            { type: 'doc', id: 'model-hub/why-model-hub', label: 'Why Model Hub' },
            { type: 'doc', id: 'model-hub/quick-start', label: 'Model Hub' },
            { type: 'doc', id: 'model-hub/sign-up-for-an-account', label: 'Sign Up For An...' },
            { type: 'doc', id: 'model-hub/top-up-balance', label: 'Top Up Balance' },
            { type: 'doc', id: 'model-hub/start-using-services', label: 'Start Using Services' },
            { type: 'doc', id: 'model-hub/notice', label: 'Model Hub' },
            { type: 'doc', id: 'model-hub/how-to-use-private-model', label: 'Model Hub' },
            { type: 'doc', id: 'model-hub/create-a-model', label: 'Create a model' },
            { type: 'doc', id: 'model-hub/view-list-model-2', label: 'View List Model 2' },
            { type: 'doc', id: 'model-hub/view-model-details', label: 'View Model Details' },
            { type: 'doc', id: 'model-hub/edit-a-model', label: 'Edit a model' },
            { type: 'doc', id: 'model-hub/delete-a-model', label: 'Delete a model' },
            { type: 'doc', id: 'model-hub/how-to-create-model-version', label: 'Create a model version' },
            { type: 'doc', id: 'model-hub/create-version', label: 'Create a version' },
            { type: 'doc', id: 'model-hub/Edit-version', label: 'Edit a version' },
            { type: 'doc', id: 'model-hub/delete-version', label: 'Delete a version' },
            { type: 'doc', id: 'model-hub/how-to-upload-download-files-by-sdk', label: 'Upload and download files by SDK' },
            { type: 'doc', id: 'model-hub/upload-files', label: 'Upload Files' },
            { type: 'doc', id: 'model-hub/download-files', label: 'Download files' },
            { type: 'doc', id: 'model-hub/delete-file', label: 'Delete a file' },
            { type: 'doc', id: 'model-hub/how-to-share-a-model', label: 'Share a model' },
            { type: 'doc', id: 'model-hub/add-share', label: 'Add share' },
            { type: 'doc', id: 'model-hub/how-to-use-model-from-other-sources-like-hugging-face', label: 'Use models from other sources' },
            { type: 'doc', id: 'model-hub/how-to-use-model-catalog', label: 'Use Model Catalog' }
          ],
        },
        {
          type: 'category',
          label: 'Model Serving',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'model-serving/model-serving', label: 'Model Serving' },
            { type: 'doc', id: 'model-serving/about-fci', label: 'About FCI' },
            { type: 'doc', id: 'model-serving/general-intro-model-serving', label: 'Overview' },
            { type: 'doc', id: 'model-serving/terms-definitions', label: 'Terms and definitions' },
            { type: 'doc', id: 'model-serving/initial-set-up', label: 'Initial setup' },
            { type: 'doc', id: 'model-serving/create-a-new-model-serving-deployment', label: 'Create a new deployment' },
            { type: 'doc', id: 'model-serving/deployment-list', label: 'Deployment list' },
            { type: 'doc', id: 'model-serving/status-actions-deployment', label: 'Status and actions' },
            { type: 'doc', id: 'model-serving/detailed-configuration-information', label: 'Detailed configuration' },
            { type: 'doc', id: 'model-serving/deployment-configuration-information', label: 'Deployment configuration' },
            { type: 'doc', id: 'model-serving/traffic-setting-configuration-information', label: 'Traffic setting' },
            { type: 'doc', id: 'model-serving/delete-a-deployment', label: 'Delete a deployment' }
          ],
        },
        {
          type: 'category',
          label: 'Model Testing - Interactive Sessions',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'model-testing-interactive-sessions/model-testing-interactive-sessions', label: 'Model Testing – Interactive...' },
            { type: 'doc', id: 'model-testing-interactive-sessions/overview', label: 'Model Testing – Interactive...' },
            { type: 'doc', id: 'model-testing-interactive-sessions/what-is-model-testing-interactive-sessions', label: 'What Is Model Testing...' },
            { type: 'doc', id: 'model-testing-interactive-sessions/when-to-use-model-testing-interactive-sessions', label: 'When To Use Model...' },
            { type: 'doc', id: 'model-testing-interactive-sessions/quick-start', label: 'Model Testing – Interactive...' },
            { type: 'doc', id: 'model-testing-interactive-sessions/sign-up-for-an-account', label: 'Sign Up For An...' },
            { type: 'doc', id: 'model-testing-interactive-sessions/step-by-step', label: 'Step By Step' },
            { type: 'doc', id: 'model-testing-interactive-sessions/how-to-create-session', label: 'How To Create Session' },
            { type: 'doc', id: 'model-testing-interactive-sessions/how-to-manage-session', label: 'How To Manage Session' },
            { type: 'doc', id: 'model-testing-interactive-sessions/status-session', label: 'Status Session' },
            { type: 'doc', id: 'model-testing-interactive-sessions/stop-session', label: 'Stop Session' },
            { type: 'doc', id: 'model-testing-interactive-sessions/delete-session', label: 'Delete Session' },
            { type: 'doc', id: 'model-testing-interactive-sessions/how-to-evaluate-model', label: 'Model Testing – Interactive...' },
            { type: 'doc', id: 'model-testing-interactive-sessions/playground', label: 'Playground' },
            { type: 'doc', id: 'model-testing-interactive-sessions/completion-history', label: 'Completion History' },
            { type: 'doc', id: 'model-testing-interactive-sessions/how-to-integrate-model', label: 'How To Integrate Model' },
            { type: 'doc', id: 'model-testing-interactive-sessions/faq', label: 'Faq' }
          ],
        },
        {
          type: 'category',
          label: 'Model Testing - Test Jobs',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'model-testing-test-jobs/model-testing-test-jobs', label: 'Model Testing – Test...' },
            { type: 'doc', id: 'model-testing-test-jobs/overview', label: 'Model Testing – Test...' },
            { type: 'doc', id: 'model-testing-test-jobs/what-is-model-testing-test-jobs', label: 'What Is Model Testing...' },
            { type: 'doc', id: 'model-testing-test-jobs/when-to-use-model-testing-test-jobs', label: 'When To Use Model...' },
            { type: 'doc', id: 'model-testing-test-jobs/quick-start', label: 'Model Testing – Test...' },
            { type: 'doc', id: 'model-testing-test-jobs/sign-up-for-an-account', label: 'Sign Up For An...' },
            { type: 'doc', id: 'model-testing-test-jobs/step-by-step', label: 'Step By Step' },
            { type: 'doc', id: 'model-testing-test-jobs/how-to-create-job', label: 'How To Create Job' },
            { type: 'doc', id: 'model-testing-test-jobs/select-model', label: 'Select Model' },
            { type: 'doc', id: 'model-testing-test-jobs/select-test-suite', label: 'Select Test Suite' },
            { type: 'doc', id: 'model-testing-test-jobs/standard-select-data-format', label: 'Standard Select Data Format' },
            { type: 'doc', id: 'model-testing-test-jobs/standard-select-test-data', label: 'Standard Select Test Data' },
            { type: 'doc', id: 'model-testing-test-jobs/standard-test-criteria', label: 'Standard Test Criteria' },
            { type: 'doc', id: 'model-testing-test-jobs/others-tasks', label: 'Others Tasks' },
            { type: 'doc', id: 'model-testing-test-jobs/set-up-parameters', label: 'Set Up Parameters' },
            { type: 'doc', id: 'model-testing-test-jobs/finish', label: 'Finish' },
            { type: 'doc', id: 'model-testing-test-jobs/how-to-manage-job', label: 'How To Manage Job' },
            { type: 'doc', id: 'model-testing-test-jobs/run-job', label: 'Run Job' },
            { type: 'doc', id: 'model-testing-test-jobs/cancel-job', label: 'Cancel Job' },
            { type: 'doc', id: 'model-testing-test-jobs/delete-job', label: 'Delete Job' },
            { type: 'doc', id: 'model-testing-test-jobs/run-history', label: 'Run History' },
            { type: 'doc', id: 'model-testing-test-jobs/how-to-evaluate-model', label: 'Model Testing – Test...' },
            { type: 'doc', id: 'model-testing-test-jobs/run-details', label: 'Run Details' },
            { type: 'doc', id: 'model-testing-test-jobs/faq', label: 'Faq' }
          ],
        },
        {
          type: 'category',
          label: 'User Token',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'user-token/user-token', label: 'User Token' },
            { type: 'doc', id: 'user-token/overview', label: 'Overview' },
            { type: 'doc', id: 'user-token/quick-start', label: 'Quick Start' },
            { type: 'doc', id: 'user-token/how-to-create-an-user-token', label: 'How To Create An...' }
          ],
        },
      ],
    },
  ],
};
