// Japanese sidebar - organized by FPT Cloud menu structure with sub-menus
module.exports = {
  tutorialSidebar: [
    'intro',
    // ========== AI Infrastructure ==========
    {
      type: 'category',
      label: 'AIインフラストラクチャ',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Managed GPU Cluster (Kubernetes)',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'managed-gpu-cluster-kubernetes-ja' }],
        },
      ],
    },
    // ========== FPT AI Factory ==========
    {
      type: 'category',
      label: 'FPT AIファクトリー',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'ai-marketplace-ja' },
        { type: 'autogenerated', dirName: 'ai-notebook-jp' },
        { type: 'autogenerated', dirName: 'data-hub-ja' },
        { type: 'autogenerated', dirName: 'model-fine-tuning-ja' },
        { type: 'autogenerated', dirName: 'gpu-virtual-machine' },
        { type: 'autogenerated', dirName: 'モデルテスト' },
      ],
    },
    // ========== Billing ==========
    {
      type: 'category',
      label: '請求',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'コストエクスプローラー' },
        { type: 'autogenerated', dirName: '予算アラート' },
      ],
    },
    // ========== FPT Cloud Server ==========
    {
      type: 'category',
      label: 'FPT クラウドサーバー',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'タグ付け (Tagging)',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'タグ-付け' }],
        },
        {
          type: 'category',
          label: 'ポリシー管理 (Policy Management)',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'ポリシー管理' }],
        },
        {
          type: 'category',
          label: 'VPCの作成 (Create VPC)',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'vpc-の作成' }],
        },
        {
          type: 'category',
          label: 'サイト間VPN (VPN Site-to-Site)',
          collapsed: true,
          items: [{ type: 'autogenerated', dirName: 'サイト間-vpn' }],
        },
      ],
    },
    // ========== Other ==========
    {
      type: 'category',
      label: 'その他のサービス',
      collapsed: true,
      items: [
        { type: 'autogenerated', dirName: 'metal-cloud-ja' },
      ],
    },
  ],
};
