// Japanese sidebar - synced with EN structure (sidebars.js)
module.exports = {
  tutorialSidebar: [
    'intro',
    // ========== FPT Cloud Server ==========
    {
      type: 'category',
      label: 'FPT Cloud Server',
      className: 'sidebar-migrated',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'タグ付け (Tagging)',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'タグ-付け/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'タグ-付け/create-tag-new', label: 'タグの作成' },
            { type: 'doc', id: 'タグ-付け/edit-tag', label: 'タグの編集' },
            { type: 'doc', id: 'タグ-付け/delete-tag', label: 'タグの削除' },
            {
              type: 'category',
              label: 'リソースのタグ管理',
              collapsed: true,
              items: [
                { type: 'doc', id: 'タグ-付け/resource-1', label: 'リソースのタグ管理' },
                { type: 'doc', id: 'タグ-付け/tags-instance', label: 'Instanceのタグ管理' },
                { type: 'doc', id: 'タグ-付け/tags-storage-disk', label: 'Storage Diskのタグ管理' },
                { type: 'doc', id: 'タグ-付け/tags-snapshot', label: 'Snapshotのタグ管理' },
                { type: 'doc', id: 'タグ-付け/tags-custom-image', label: 'Custom Imageのタグ管理' },
                { type: 'doc', id: 'タグ-付け/tags-floating-ip', label: 'Floating IPのタグ管理' },
                { type: 'doc', id: 'タグ-付け/tags-subnet', label: 'Subnetのタグ管理' },
                { type: 'doc', id: 'タグ-付け/tags-security-group', label: 'Security Groupのタグ管理' },
                { type: 'doc', id: 'タグ-付け/tagg-lb', label: 'Load Balancerのタグ管理' },
              ],
            },
            { type: 'doc', id: 'タグ-付け/tagging-billing', label: 'タグ別請求' },
          ],
        },
        {
          type: 'category',
          label: 'クラウドサーバー (Cloud Server)',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'cloud-server/cloud-server', label: '概要' },
            { type: 'doc', id: 'cloud-server/Initial-Setup', label: '初期設定' },
            { type: 'doc', id: 'cloud-server/quick-starts-tao-mot-may-ao', label: '仮想マシンの作成' },
            { type: 'doc', id: 'cloud-server/create-vm-iso', label: 'ISOファイルからのVM作成時の注意事項' },
            { type: 'doc', id: 'cloud-server/clone-instance', label: '仮想マシンのクローン' },
            { type: 'doc', id: 'cloud-server/quick-starts-tatbat-may-ao', label: '仮想マシンの起動/停止' },
            { type: 'doc', id: 'cloud-server/quick-starts-khoi-dong-lai-may-ao', label: '仮想マシンの再起動' },
            { type: 'doc', id: 'cloud-server/lock-unlock-instance-deletion', label: '削除ロック & ロック解除' },
            { type: 'doc', id: 'cloud-server/quick-starts-xoa-may-ao', label: '仮想マシンの削除' },
            { type: 'doc', id: 'cloud-server/quan-ly-may-ao', label: '仮想マシンの管理' },
            { type: 'doc', id: 'cloud-server/tutorials-khoi-tao-mot-may-ao-moi', label: '新しい仮想マシンの作成' },
            { type: 'doc', id: 'cloud-server/tutorials-ket-noi-vao-may-ao-windows', label: 'Windows仮想マシンへの接続' },
            { type: 'doc', id: 'cloud-server/tutorials-ket-noi-vao-may-ao-linux', label: 'Linux仮想マシンへの接続' },
            { type: 'doc', id: 'cloud-server/attach-a-network-card-to-the-virtual-machine', label: '仮想マシンへのNIC追加' },
            { type: 'doc', id: 'cloud-server/remove-the-network-card-from-the-virtual-machine', label: '仮想マシンからのNIC削除' },
            { type: 'doc', id: 'cloud-server/tutorials-tra-cuu-thong-tin-thong-so-ky-thuat-cua-may-ao-da-tao', label: '仮想マシン情報の確認' },
            { type: 'doc', id: 'cloud-server/tutorials-thay-doi-thong-tin-cau-hinh-may-chu', label: '仮想マシン構成の変更' },
            { type: 'doc', id: 'cloud-server/tutorials-backup-may-chu-voi-snapshot', label: 'Snapshotによるバックアップ' },
            { type: 'doc', id: 'cloud-server/tutorials-xoa-may-ao', label: '仮想マシンの削除' },
            { type: 'doc', id: 'cloud-server/GPU', label: 'Portal ConsoleでのGPU管理' },
            { type: 'doc', id: 'cloud-server/gpu-general', label: 'Console PortalでのGPU管理' },
            { type: 'doc', id: 'cloud-server/gpu-specific', label: 'SpecificサービスのGPU管理' },
            { type: 'doc', id: 'cloud-server/quan-ly-gpu-voi-hpc-portal', label: 'HPC PortalでのGPU Server管理' },
            { type: 'doc', id: 'cloud-server/hpc-quick-start', label: 'クイックスタート' },
            { type: 'doc', id: 'cloud-server/hpc-change-package', label: 'マシン設定の変更' },
            { type: 'doc', id: 'cloud-server/hpc-fixed-rental', label: '固定レンタル期間の設定' },
            { type: 'doc', id: 'cloud-server/hpc-snapshot-backup', label: 'Snapshotバックアップ' },
            { type: 'doc', id: 'cloud-server/hpc-hardware-fixation', label: 'ハードウェア固定' },
            { type: 'doc', id: 'cloud-server/hpc-rest-machine', label: 'マシンのリセット' },
            { type: 'doc', id: 'cloud-server/hpc-schedule-shutdown', label: 'シャットダウンスケジュール' },
            { type: 'doc', id: 'cloud-server/hpc-clone-image', label: 'Imageのクローン' },
            { type: 'doc', id: 'cloud-server/hpc-level-2-password', label: '第2レベルパスワードの設定' },
            { type: 'doc', id: 'cloud-server/hpc-delete-image', label: 'Imageの削除' },
            { type: 'doc', id: 'cloud-server/block-storage', label: 'Block Storage' },
            { type: 'doc', id: 'cloud-server/tao-storage-disk', label: 'Storage Disk の作成' },
            { type: 'doc', id: 'cloud-server/gan-storage-disk-vao-may-ao', label: 'Storage Disk を Instance にアタッチする' },
            { type: 'doc', id: 'cloud-server/cau-hinh-o-dia-cho-may-ao-chay-windows', label: 'Windows Instance のディスクを設定する' },
            { type: 'doc', id: 'cloud-server/go-storage-disk-khoi-may-ao', label: 'Storage Disk を Instance からデタッチする' },
            { type: 'doc', id: 'cloud-server/edit-storage-disk', label: 'Storage Disk の編集' },
            { type: 'doc', id: 'cloud-server/xoa-storage-disk', label: 'Storage Disk の削除' },
            { type: 'doc', id: 'cloud-server/profile-ssh-key', label: 'SSH Key' },
            { type: 'doc', id: 'cloud-server/token', label: 'Token' },
            { type: 'doc', id: 'cloud-server/create-token', label: 'Token の作成' },
            { type: 'doc', id: 'cloud-server/revoke-token', label: 'Revoke Token' },
            { type: 'doc', id: 'cloud-server/FQAs', label: 'よくある質問' },
            { type: 'doc', id: 'cloud-server/custom-images-overview', label: 'Custom Images Overview' },
            { type: 'doc', id: 'cloud-server/tai-len-custom-image', label: 'Custom Image のアップロード' },
            { type: 'doc', id: 'cloud-server/xoa-custom-image', label: 'Custom Image の削除' },
            { type: 'doc', id: 'cloud-server/tutorials-quan-ly-instance-template', label: 'Instance Templateの管理' },
            { type: 'doc', id: 'cloud-server/tutorials-khoi-tao-template-tu-may-ao', label: '仮想マシンからTemplateを作成する' },
            { type: 'doc', id: 'cloud-server/tutorials-quan-ly-template-duoc-tao-tu-may-ao', label: 'Custom ImagesでTemplateを管理する' },
            { type: 'doc', id: 'cloud-server/tutorials-tao-instance-tu-template', label: 'TemplateからInstanceを作成する' },
            { type: 'doc', id: 'cloud-server/tutorials-xoa-template', label: 'Templateを削除する' },
            { type: 'doc', id: 'cloud-server/nat-instance', label: 'NAT Instance' },
            { type: 'doc', id: 'cloud-server/NIC-overview-1', label: 'NICの管理' },
            { type: 'doc', id: 'cloud-server/overview-nic', label: '概要' },
            { type: 'doc', id: 'cloud-server/create-card-NIC- Primary', label: 'Primary NICカードを作成する' },
            { type: 'doc', id: 'cloud-server/disable-NIC-card', label: 'Network Interface Cardを無効化する' },
            { type: 'doc', id: 'cloud-server/enable-NIC-card', label: 'Network Interface Cardを有効化する' },
            { type: 'doc', id: 'cloud-server/add-card-NIC- new', label: '新しいNetwork Interface Cardを追加する' },
            { type: 'doc', id: 'cloud-server/convert-card', label: 'カードをPrimaryに変換する' },
            { type: 'doc', id: 'cloud-server/edit-ip-address', label: 'IP Addressを編集する' },
            { type: 'doc', id: 'cloud-server/change-address-MAC', label: 'MACアドレスを変更する' },
            { type: 'doc', id: 'cloud-server/delete-card-NIC', label: 'Network Interface Cardを削除する' },
            { type: 'doc', id: 'cloud-server/change-network-config', label: 'Network Configを変更する' },
            { type: 'doc', id: 'cloud-server/network-all', label: 'ネットワーキング概要' },
            { type: 'doc', id: 'cloud-server/networking-overview', label: 'ネットワーキング詳細' },
            { type: 'doc', id: 'cloud-server/gateway', label: 'Gateway' },
            { type: 'doc', id: 'cloud-server/quan-ly-floating-ip', label: 'Floating IP管理' },
            { type: 'doc', id: 'cloud-server/Quản lý Subnets', label: 'Subnet管理' },
            { type: 'doc', id: 'cloud-server/allow-address-pair', label: 'Allow Address Pair' },
            { type: 'doc', id: 'cloud-server/quan-ly-security-group', label: 'Security Group管理' },
            { type: 'doc', id: 'cloud-server/security-group-filter', label: 'Security Groupのフィルター' },
            { type: 'doc', id: 'cloud-server/security-group-priority-rule', label: 'Priority Rule管理' },
            { type: 'doc', id: 'cloud-server/overview-bell', label: '通知ベル' },
            { type: 'doc', id: 'cloud-server/terraform', label: 'IaC (Terraform)' },
            { type: 'doc', id: 'cloud-server/instance-group', label: 'Instance Group — Affinity & Anti-Affinity' },
            { type: 'doc', id: 'cloud-server/overview-affinity', label: '概要' },
            { type: 'doc', id: 'cloud-server/create-instance-group', label: 'Instance Groupの作成' },
            { type: 'doc', id: 'cloud-server/edit-instance-group-specific', label: 'Instance Groupの編集' },
            { type: 'doc', id: 'cloud-server/add-instance-instance-group', label: 'InstanceをGroupに追加' },
            { type: 'doc', id: 'cloud-server/delete-instance-group', label: 'Instance Groupの削除' },
            { type: 'doc', id: 'cloud-server/project-structure', label: 'Project管理' },
            { type: 'doc', id: 'cloud-server/quan-ly-project', label: 'Project管理の詳細' },
            { type: 'doc', id: 'cloud-server/select-project-when-creating-VPC', label: 'VPC作成時のProject選択' },
            { type: 'doc', id: 'cloud-server/header-project', label: 'ヘッダーインターフェースの変更' },
            { type: 'doc', id: 'cloud-server/new-quota', label: 'PAYGサービス' },
            { type: 'doc', id: 'cloud-server/instance-schedule', label: 'インスタンス起動・停止スケジュール' },
            { type: 'doc', id: 'cloud-server/schedule-overview', label: '概要' },
            { type: 'doc', id: 'cloud-server/create-new-instance', label: 'Instance Scheduleの作成' },
            { type: 'doc', id: 'cloud-server/view-detail-instance', label: '詳細の確認' },
            { type: 'doc', id: 'cloud-server/attach-schedule-to-instance', label: 'InstanceをScheduleにアタッチ' },
            { type: 'doc', id: 'cloud-server/detach-schedule-to-instance', label: 'InstanceをScheduleからデタッチ' },
            { type: 'doc', id: 'cloud-server/delete-instance-schedule', label: 'Instance Scheduleの削除' },
            { type: 'doc', id: 'cloud-server/schedule-snapshotVM', label: 'インスタンスSnapshotスケジュール' },
            { type: 'doc', id: 'cloud-server/create-schedule-snapshotVM', label: 'インスタンスSnapshotスケジュールの作成' },
            { type: 'doc', id: 'cloud-server/viewschedule-snapshotVM', label: '詳細の確認' },
            { type: 'doc', id: 'cloud-server/editschedule-snapshotVM', label: '編集' },
            { type: 'doc', id: 'cloud-server/deleteschedule-snapshotVM', label: 'インスタンスSnapshotスケジュールの削除' },
            { type: 'doc', id: 'cloud-server/schedule-snapshotstorage', label: 'ストレージディスクSnapshotスケジュール' },
            { type: 'doc', id: 'cloud-server/createschedule-snapshotstorage', label: 'ストレージディスクSnapshotスケジュールの作成' },
            { type: 'doc', id: 'cloud-server/viewschedule-snapshotstorage', label: '詳細の確認' },
            { type: 'doc', id: 'cloud-server/editschedule-snapshotstorage', label: '編集' },
            { type: 'doc', id: 'cloud-server/deleteschedule-snapshotstorage', label: 'ストレージディスクSnapshotスケジュールの削除' },
            { type: 'doc', id: 'cloud-server/question-2', label: 'FAQ：Security Groupルールのカスタマイズ' },
            { type: 'doc', id: 'cloud-server/question-1', label: 'FAQ：Address Pairの編集' },
            { type: 'doc', id: 'cloud-server/question-', label: 'FAQ：NAT Instance' }
          ],
        },
      ],
    },
    // ========== FPT Container ==========
    {
      type: 'category',
      label: 'FPT Container',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Managed FPT Kubernetes Engine',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/index', label: 'Managed FPT Kubernetes Engine' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/Initial-setup', label: '初期設定' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/quan-ly-kubernetes-cluster', label: 'Kubernetes Cluster の管理' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/khoi-tao-kubernetes-cluster-moi', label: '新しい Kubernetes Cluster の作成' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/xem-danh-sach-kubernetes-cluster-da-tao', label: '作成済み Kubernetes Cluster の一覧表示' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/truy-cap-thong-tin-chi-tiet-cua-cluster', label: 'クラスターの詳細情報へのアクセス' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/lay-thong-tin-truy-cap-cluster', label: 'クラスターのアクセス情報の取得' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/tinh-nang-rotate-kubeconfig', label: 'kubeconfig のローテーション機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/xoa-kubernetes-cluster', label: 'Kubernetes Cluster の削除' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/thay-doi-cau-hinh-k8s-cluster', label: 'K8s Cluster の設定変更' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/thay-doi-cluster-endponit-access', label: 'クラスターエンドポイントアクセスの変更' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/them-worker-group', label: 'ワーカーグループの追加' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/thay-doi-cau-hinh-internal-subnet-load-balancer', label: 'Internal subnet Load Balancer（CIDR）設定の変更' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/chinh-sua-label-taint-cho-worker-group', label: 'ワーカーグループの label/taint 設定変更' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/enable-cluster-autoscale', label: 'Cluster Autoscale の有効化' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/disable-cluster-autoscale', label: 'Cluster Autoscale の無効化' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/bat-tat-node-auto-repair', label: 'Node Auto-repair の有効化/無効化' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/chuyen-worker-group-base', label: 'ベースワーカーグループの切り替え' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/modify-cluster-autoscale-configuration', label: 'Cluster Autoscale 構成の変更' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/nang-cap-k8s-version', label: 'K8S バージョンのアップグレード' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/cluster-autoscale', label: 'Cluster Autoscale の有効化' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/load-balancer-services', label: 'Load Balancer サービス' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/trien-khai-ung-dung-tren-worker-pool', label: 'ワーカープールへのアプリケーションのデプロイ' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/how-to-use-gpu-in-kubernetes', label: 'Kubernetes での GPU の使用' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/scale-in-chi-dinh-node', label: 'クラスター内の特定 node を指定したスケールイン機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/service-type-load-balancer', label: 'Service Type Load-Balancer' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/setup-k8s-cluster-for-gpu-usage', label: 'GPU 用クラスターのセットアップ' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/addding-gpu-worker-group', label: 'GPU Worker Group の追加' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/persistent-storage', label: 'Persistent Storage' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/deploy-application-with-gpu-on-k8s', label: 'GPU アプリのデプロイ' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/tinh-nang-hibernate-wakeup', label: 'Hibernate & Wake-up 機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/tinh-nang-dat-lich-hibernate-wake-up', label: 'Hibernate & Wake-up スケジュール機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/setting-up-gpu-telemetry', label: 'GPU テレメトリーの設定' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/tu-dong-nang-cap-version', label: 'バージョン自動アップグレード機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/container-level-auto-scaling', label: 'コンテナレベルの自動スケーリング' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/node-level-auto-scaling', label: 'ノードレベルの自動スケーリング' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/gioi-thieu-chung-ve-quy-trinh-quan-ly-version', label: 'FPTCloud における Kubernetes バージョン管理プロセスの概要' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/huong-dan-chi-tiet-su-dung-auto-upgrade', label: 'auto upgrade version 機能の詳細ガイド' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/fpt-cloud-managed-kubernetes-release-calendar', label: 'FPT Cloud Managed Kubernetes リリースカレンダー' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/tinh-nang-tang-cuong-bao-mat-mfke', label: 'M-FKE のセキュリティ強化機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/tinh-nang-benchmark-cluster', label: 'Managed Kubernetes Cluster のベンチマーク機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/tinh-nang-runtime-security-cluster', label: 'Runtime Security 機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/tinh-nang-workload-scan', label: 'ワークロードスキャン機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/audit-log-vn', label: 'Audit Logs Security 機能の概要' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/danh-tag-cho-vm', label: '仮想マシンへのタグ付け機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/backup-restore-vn', label: 'Backup & Restore 機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/cac-luu-y-khi-su-dung-m-fke', label: 'M-FKE 使用上の注意事項' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/mfke-faqs', label: 'よくある質問' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/microservices-architecture-on-fke', label: 'FKE 上のマイクロサービスアーキテクチャ' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/gpu-la-gi', label: 'GPU とは？' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/tai-sao-nen-su-dung-gpu-tren-cloud', label: 'クラウドで GPU を使用する理由' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/tai-sao-nen-su-dung-gpu-tren-kubernetes', label: 'Kubernetes で GPU を使用する理由' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/gpu-sharing', label: 'GPU Sharing' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/dich-vu-gpu-tren-k8s', label: 'Kubernetes 上の GPU サービス' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/dieu-chinh-cau-hinh-coredns-trong-kubernetes-service', label: 'CoreDNS 設定の調整' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/snapshot-va-restore-pvc-tren-k8s-fpt', label: 'PVC のスナップショットとリストア' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/snapshot-persistent-volume-tren-k8s', label: 'Persistent Volume のスナップショット機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/restore-persistent-volume-tren-k8s', label: 'スナップショットからの volume リストア機能' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/thuc-hien-dat-lich-snapshot-pvc', label: 'PVC スナップショットのスケジュール設定' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/thuc-hien-dat-lich-xoa-pvc-snapshot', label: 'PVC スナップショット削除スケジュールの設定' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/cau-hinh-proxy-protocol', label: 'Proxy Protocol の設定' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/cau-hinh-proxy-protocol-cho-istio-ingress', label: 'istio-ingress の Proxy Protocol 設定' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/cau-hinh-proxy-protocol-cho-nginx-ingress', label: 'nginx-ingress の Proxy Protocol 設定' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/service-type-kb-layer7-lbv2', label: 'Service Type Loadbalancer Layer 7（LBv2）の使用' },
            { type: 'doc', id: 'managed-fpt-kubernetes-engine/thay-doi-cau-hinh-flavor-cua-worker-pool', label: 'ワーカープールのフレーバー設定変更' }
          ],
        },
        {
          type: 'category',
          label: 'FPT Container Registry',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-container-registry/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'fpt-container-registry/enabling-fpt-container-registry-service', label: 'サービスの有効化' },
            { type: 'doc', id: 'fpt-container-registry/docker-login', label: 'Docker Login' },
            { type: 'doc', id: 'fpt-container-registry/tagging-and-pushing-images', label: 'イメージのタグ付けとプッシュ' },
            { type: 'doc', id: 'fpt-container-registry/pulling-docker-image', label: 'Dockerイメージのプル' },
            { type: 'doc', id: 'fpt-container-registry/managing-repositories', label: 'リポジトリの管理' },
            { type: 'doc', id: 'fpt-container-registry/scan-image', label: 'イメージのスキャン' },
            { type: 'doc', id: 'fpt-container-registry/retention-rule', label: 'Retention Rule' },
            { type: 'doc', id: 'fpt-container-registry/robot-account', label: 'Robot Account' },
          ],
        },
        {
          type: 'category',
          label: 'Dedicated FPT Kubernetes Engine',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/dedicated-fpt-kubernetes-engine', label: 'Dedicated FPT Kubernetes Engine' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/managing-k8s-cluster', label: 'Kubernetes クラスターの管理' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/create-new-k8s-cluster', label: '新規 Kubernetes cluster の作成' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/list-created-clusters', label: 'クラスター一覧の表示' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/access-clusters-detail-information', label: 'クラスター詳細情報へのアクセス' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/get-cluster-access-information', label: 'cluster アクセス情報の取得' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/delete-k8s-cluster', label: 'クラスターの削除' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/stop-k8s-cluster', label: 'クラスターの停止' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/start-k8s-cluster', label: 'クラスターの起動' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/changing-cluster-configuration', label: 'クラスター構成の変更' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/scale-worker-nodes', label: 'Worker Nodes のスケール' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/change-nodes-configuration', label: 'Nodes 構成の変更' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/change-nfs-server-configuration', label: 'NFS Server 構成の変更' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/increase-storage-size-of-nodes', label: 'Nodes ストレージサイズの拡張' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/increase-storage-size-of-nfs-server', label: 'NFS Server ストレージサイズの拡張' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/upgrade-k8s-version', label: 'Kubernetes バージョンのアップグレード' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/upgrading-k8s-version', label: 'K8s バージョンのアップグレード' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/add-nfs-storage', label: 'NFS Persistent Storage の追加' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/auto-scale', label: 'Autoscale' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/manual-scale', label: 'Manual Scale' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/best-practice-manual-scaling', label: 'Manual Scaling ベストプラクティス' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/persistent-storage', label: 'Persistent Storage' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/load-balancer-services', label: 'Service Type Load-Balancer' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/advanced-firewall', label: 'Advanced Firewall' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/backup-restore-cluster', label: 'Cluster のバックアップとリストア' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/best-practice-upgrade-version', label: 'バージョンアップグレード ベストプラクティス' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/auto-repair-nodes', label: 'Auto Repair Nodes' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/fke-usage-notes', label: 'FKE 使用上の注意事項' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/notes-when-using-dfke', label: 'FKE 使用時の注意事項' },
            { type: 'doc', id: 'dedicated-fpt-kubernetes-engine/faqs', label: 'よくある質問' }
          ],
        },
      ],
    },
    // ========== FPT Network ==========
    {
      type: 'category',
      label: 'FPT Network',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'サイト間VPN (VPN Site-to-Site)',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'vpn-site-to-site/サイト間-vpn', label: 'サイト間 VPN' },
            { type: 'doc', id: 'vpn-site-to-site/サイト間VPNの作成 -1', label: 'サイト間VPNの作成' },
            { type: 'doc', id: 'vpn-site-to-site/VPN情報の確認', label: 'VPN情報の確認' },
            { type: 'doc', id: 'vpn-site-to-site/サイト間VPNの無効化 -1', label: 'サイト間VPNの無効化' },
            { type: 'doc', id: 'vpn-site-to-site/サイト間VPNを有効にする-2', label: 'サイト間VPNの有効化' },
            { type: 'doc', id: 'vpn-site-to-site/サイト間VPNの情報編集 -3', label: 'VPN情報の編集' },
            { type: 'doc', id: 'vpn-site-to-site/サイト間VPNの構成情報をダウンロード', label: 'VPN構成情報のダウンロード' },
            { type: 'doc', id: 'vpn-site-to-site/サイト間の削除-5', label: 'サイト間VPNの削除' },
            { type: 'doc', id: 'vpn-site-to-site/VPNアクティビティの確認', label: 'VPN Activity logの確認' },
            { type: 'doc', id: 'vpn-site-to-site/認証証明書モード', label: '証明書認証モード' }
          ],
        },
        {
          type: 'category',
          label: 'ロードバランサー (Load Balancer)',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'load-balancer/initial-setup', label: '初期設定' },
            {
              type: 'category',
              label: 'Load Balancer (チュートリアル)',
              collapsed: true,
              items: [
                {
                  type: 'category',
                  label: 'Load Balancerの管理',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'load-balancer/create-load-balancer', label: 'Load Balancerの作成' },
                    { type: 'doc', id: 'load-balancer/update-load-balancer', label: 'Load Balancerの更新' },
                    { type: 'doc', id: 'load-balancer/monitor-load-balancer', label: '監視チャート' },
                    { type: 'doc', id: 'load-balancer/add-external-member', label: 'External Memberの追加' },
                    { type: 'doc', id: 'load-balancer/resize-load-balancer', label: 'Load Balancerのリサイズ' },
                    { type: 'doc', id: 'load-balancer/access-logs', label: 'アクセスログ' },
                    { type: 'doc', id: 'load-balancer/integrate-with-fmon', label: 'FMONとの統合' },
                  ],
                },
                {
                  type: 'category',
                  label: 'Listenerの管理',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'load-balancer/create-listener', label: 'Listenerの作成' },
                    { type: 'doc', id: 'load-balancer/configure-timeout', label: 'タイムアウトの設定' },
                    { type: 'doc', id: 'load-balancer/configure-l7-policy', label: 'L7ポリシーの設定' },
                    { type: 'doc', id: 'load-balancer/redirect-http-to-https', label: 'HTTPからHTTPSへのリダイレクト' },
                    { type: 'doc', id: 'load-balancer/redirect-prefix', label: 'プレフィックスリダイレクト' },
                    { type: 'doc', id: 'load-balancer/enable-hsts', label: 'HSTSの有効化' },
                    { type: 'doc', id: 'load-balancer/allow-ip-cidr', label: 'IP/CIDRの許可設定' },
                    { type: 'doc', id: 'load-balancer/configure-sni', label: 'SNIの設定' },
                  ],
                },
                {
                  type: 'category',
                  label: 'Server Poolの管理',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'load-balancer/create-server-pool', label: 'Server Poolの作成' },
                    { type: 'doc', id: 'load-balancer/manage-pool-members', label: 'メンバーの追加・削除' },
                    { type: 'doc', id: 'load-balancer/configure-health-check', label: 'ヘルスチェックの設定' },
                  ],
                },
                {
                  type: 'category',
                  label: 'SSL証明書の管理',
                  collapsed: true,
                  items: [
                    { type: 'doc', id: 'load-balancer/import-ssl-certificate', label: 'SSL証明書のインポート' },
                    { type: 'doc', id: 'load-balancer/delete-ssl-certificate', label: 'SSL証明書の削除' },
                  ],
                },
              ],
            },
            {
              type: 'category',
              label: 'Classic Load Balancer (チュートリアル)',
              collapsed: true,
              items: [
                { type: 'doc', id: 'load-balancer/classic-create-load-balancer', label: 'Classic LBの作成' },
                { type: 'doc', id: 'load-balancer/classic-add-instance', label: 'VMの追加' },
                { type: 'doc', id: 'load-balancer/classic-remove-instance', label: 'VMの削除' },
                { type: 'doc', id: 'load-balancer/classic-update-load-balancer', label: 'Classic LBの更新' },
                { type: 'doc', id: 'load-balancer/classic-delete-load-balancer', label: 'Classic LBの削除' },
                { type: 'doc', id: 'load-balancer/classic-import-ssl-certificate', label: 'SSL証明書のインポート' },
                { type: 'doc', id: 'load-balancer/classic-view-ssl-certificate', label: 'SSL証明書の確認' },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'VPCの作成 (Create VPC)',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'create-vpc/vpc-の作成', label: 'VPC の作成' },
            { type: 'doc', id: 'create-vpc/初期設定_1', label: '初期設定' },
            { type: 'doc', id: 'create-vpc/VPC の作成_1', label: 'VPCを作成する' },
            { type: 'doc', id: 'create-vpc/アクティビティログの表示_2', label: 'VPCの名前変更' },
            { type: 'doc', id: 'create-vpc/アクティビティログ＆直近タスクステータスの記録_3', label: 'Activity logとタスクステータスの確認' }
          ],
        },
      ],
    },
    // ========== FPT Storage ==========
    {
      type: 'category',
      label: 'FPT Storage',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'FPT Object Storage',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-object-storage/object-storage', label: '概要' },
            { type: 'doc', id: 'fpt-object-storage/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'fpt-object-storage/use-on-fpt-portal', label: 'FPT Portal での利用' },
            { type: 'doc', id: 'fpt-object-storage/manage-bucket', label: 'bucket の管理' },
            { type: 'doc', id: 'fpt-object-storage/manage-objects', label: 'object の管理' },
            { type: 'doc', id: 'fpt-object-storage/manage-permissions', label: 'Permissions' },
            { type: 'doc', id: 'fpt-object-storage/bucket-config', label: 'bucket の設定' },
            { type: 'doc', id: 'fpt-object-storage/encryption', label: '暗号化（SSE-C）' },
            { type: 'doc', id: 'fpt-object-storage/manage-access-keys', label: 'access key の管理' },
            { type: 'doc', id: 'fpt-object-storage/manage-subusers', label: 'subuser の管理' },
            { type: 'doc', id: 'fpt-object-storage/use-with-s3-browser', label: 'S3 Browser での利用' },
            { type: 'doc', id: 'fpt-object-storage/integrate-s3-clients', label: 'S3 クライアントとの統合' },
            { type: 'doc', id: 'fpt-object-storage/sdk-api-reference', label: 'SDK・API リファレンス' },
            { type: 'doc', id: 'fpt-object-storage/migrate-bucket-data', label: 'bucket データの移行' },
            { type: 'doc', id: 'fpt-object-storage/use-as-media-server', label: 'メディアサーバーとして使用' },
            { type: 'doc', id: 'fpt-object-storage/build-static-website', label: '静的ウェブサイトの構築' },
            { type: 'doc', id: 'fpt-object-storage/mount-bucket-local', label: 'ローカルへの bucket マウント' },
            { type: 'doc', id: 'fpt-object-storage/clone-bucket-data', label: 'bucket 間のデータクローン' },
            { type: 'doc', id: 'fpt-object-storage/subuser-bucket-permissions', label: 'subuser への bucket 権限付与' }
          ],
        },
      ],
    },
    // ========== FPT Database Engine ==========
    {
      type: 'category',
      label: 'FPT Database Engine',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Managed FPT Database Engine',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'managed-fpt-database-engine/managed-fpt-database-engine', label: 'Managed FPT Database Engine' },
            { type: 'doc', id: 'managed-fpt-database-engine/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'managed-fpt-database-engine/create-security-groups', label: 'セキュリティグループの作成' },
            { type: 'doc', id: 'managed-fpt-database-engine/create-floating-ip', label: 'floating IP の作成' },
            { type: 'doc', id: 'managed-fpt-database-engine/create-subnets', label: 'subnet の作成' },
            { type: 'doc', id: 'managed-fpt-database-engine/database-feature-permissions', label: 'Database 機能の権限設定' },
            { type: 'doc', id: 'managed-fpt-database-engine/roles', label: 'ロールの管理' },
            { type: 'doc', id: 'managed-fpt-database-engine/provision-database-engine', label: 'Database Engine のプロビジョニング' },
            { type: 'doc', id: 'managed-fpt-database-engine/create-database-engine', label: 'Database Engine の作成' },
            { type: 'doc', id: 'managed-fpt-database-engine/manage-database-engine', label: 'Database Engine の管理' },
            { type: 'doc', id: 'managed-fpt-database-engine/manage-backups', label: 'バックアップの管理' },
            { type: 'doc', id: 'managed-fpt-database-engine/create-backup-service', label: 'バックアップサービスの作成' },
            { type: 'doc', id: 'managed-fpt-database-engine/update-delete-backup-job', label: 'バックアップジョブの更新と削除' },
            { type: 'doc', id: 'managed-fpt-database-engine/update-delete-backup-service', label: 'バックアップサービスの更新と削除' },
            { type: 'doc', id: 'managed-fpt-database-engine/manage-restore', label: 'リストアの管理' },
            { type: 'doc', id: 'managed-fpt-database-engine/manage-resources', label: 'リソースの管理' },
            { type: 'doc', id: 'managed-fpt-database-engine/manage-configuration', label: 'Configuration の管理' },
            { type: 'doc', id: 'managed-fpt-database-engine/process-monitoring', label: 'プロセスモニタリングの管理' },
            { type: 'doc', id: 'managed-fpt-database-engine/manage-event-logs', label: 'イベントログの管理' },
            { type: 'doc', id: 'managed-fpt-database-engine/db-proxy', label: 'DB proxy' },
            { type: 'doc', id: 'managed-fpt-database-engine/create-db-proxy', label: 'DB proxy の作成' },
            { type: 'doc', id: 'managed-fpt-database-engine/manage-db-proxy', label: 'DB proxy の管理' }
          ],
        },
      ],
    },
    // ========== FPT Integration ==========
    {
      type: 'category',
      label: 'FPT Integration',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'FPT Message Bus (RabbitMQ)',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-message-bus/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'fpt-message-bus/quick-starts', label: 'クイックスタート' },
            {
              type: 'category',
              label: 'Queuesの管理',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-message-bus/manage-queues', label: 'Queuesの管理' },
                { type: 'doc', id: 'fpt-message-bus/create-queues', label: 'Queueの作成' },
                { type: 'doc', id: 'fpt-message-bus/view-queues', label: 'Queueの表示' },
                { type: 'doc', id: 'fpt-message-bus/delete-queues', label: 'Queueの削除' },
                { type: 'doc', id: 'fpt-message-bus/send-receive-messages-in-queues', label: 'Queueのメッセージ送受信' },
              ],
            },
            {
              type: 'category',
              label: 'Topicsの管理',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-message-bus/manage-topics', label: 'Topicsの管理' },
                { type: 'doc', id: 'fpt-message-bus/create-topics', label: 'Topicの作成' },
                { type: 'doc', id: 'fpt-message-bus/create-subscriptions', label: 'Subscriptionの作成' },
                { type: 'doc', id: 'fpt-message-bus/edit-topics', label: 'Topicの編集' },
                { type: 'doc', id: 'fpt-message-bus/delete-topics', label: 'Topicの削除' },
                { type: 'doc', id: 'fpt-message-bus/send-receive-messages-in-topics', label: 'Topicのメッセージ送受信' },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'FPT Kafka',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-kafka/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'fpt-kafka/quick-starts', label: 'クイックスタート' },
            {
              type: 'category',
              label: 'Topicsの管理',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-kafka/manage-topics', label: 'Topicsの管理' },
                { type: 'doc', id: 'fpt-kafka/create-topics', label: 'Topicの作成' },
                { type: 'doc', id: 'fpt-kafka/view-topics', label: 'Topicの表示' },
                { type: 'doc', id: 'fpt-kafka/edit-topics', label: 'Topicの編集' },
                { type: 'doc', id: 'fpt-kafka/delete-topics', label: 'Topicの削除' },
              ],
            },
            {
              type: 'category',
              label: 'Consumer Groupsの管理',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-kafka/manage-consumer-groups', label: 'Consumer Groupsの管理' },
                { type: 'doc', id: 'fpt-kafka/create-consumer-groups', label: 'Consumer Groupの作成' },
                { type: 'doc', id: 'fpt-kafka/view-consumer-groups', label: 'Consumer Groupの表示' },
                { type: 'doc', id: 'fpt-kafka/delete-consumer-groups', label: 'Consumer Groupの削除' },
              ],
            },
            {
              type: 'category',
              label: 'Credentialsの管理',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-kafka/manage-credentials', label: 'Credentialsの管理' },
                { type: 'doc', id: 'fpt-kafka/create-credentials', label: 'Credentialの作成' },
                { type: 'doc', id: 'fpt-kafka/edit-credentials', label: 'Credentialの編集' },
                { type: 'doc', id: 'fpt-kafka/delete-credentials', label: 'Credentialの削除' },
              ],
            },
            {
              type: 'category',
              label: 'ACLsの管理',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-kafka/manage-acls', label: 'ACLsの管理' },
                { type: 'doc', id: 'fpt-kafka/create-acls', label: 'ACLの作成' },
                { type: 'doc', id: 'fpt-kafka/delete-acls', label: 'ACLの削除' },
              ],
            },
            { type: 'doc', id: 'fpt-kafka/demo', label: 'Demo' },
          ],
        },
        {
          type: 'category',
          label: 'FPT API Management',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-api-management/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'fpt-api-management/quick-starts', label: 'クイックスタート' },
            { type: 'doc', id: 'fpt-api-management/registering-on-fpt-portal', label: 'FPT Portalでのサービス登録' },
            { type: 'doc', id: 'fpt-api-management/declaring-information', label: 'ApiManagerでの情報設定' },
            { type: 'doc', id: 'fpt-api-management/manage-rest-apis', label: 'REST APIの管理' },
            { type: 'doc', id: 'fpt-api-management/managing-products', label: 'Productの管理' },
            { type: 'doc', id: 'fpt-api-management/managing-sites', label: 'API Siteの管理' },
            { type: 'doc', id: 'fpt-api-management/managing-consumers', label: 'Consumerの管理' },
            { type: 'doc', id: 'fpt-api-management/analytics', label: 'Analytics' },
            { type: 'doc', id: 'fpt-api-management/consumer-api-usage-guide', label: 'API Consumer向け利用ガイド' },
          ],
        },
      ],
    },
    // ========== FPT DevSecOps Services ==========
    {
      type: 'category',
      label: 'FPT DevSecOps Services',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'FPT Key Vault',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-key-vault/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'fpt-key-vault/create-vault-instance', label: 'Vault Instanceの作成' },
            {
              type: 'category',
              label: 'Secret Engine管理',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-key-vault/secret-engine-management', label: 'Secret Engine管理' },
                { type: 'doc', id: 'fpt-key-vault/create-secret-engine', label: 'Secret Engineの作成' },
                { type: 'doc', id: 'fpt-key-vault/delete-secret-engine', label: 'Secret Engineの削除' },
              ],
            },
            {
              type: 'category',
              label: 'Secret管理',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-key-vault/secret-management', label: 'Secret管理' },
                { type: 'doc', id: 'fpt-key-vault/create-secret', label: 'Secretの作成' },
                { type: 'doc', id: 'fpt-key-vault/view-update-secret', label: 'Secretの表示・更新' },
                { type: 'doc', id: 'fpt-key-vault/delete-secret', label: 'Secretの削除' },
              ],
            },
            {
              type: 'category',
              label: 'Policy管理',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-key-vault/policy-management', label: 'Policy管理' },
                { type: 'doc', id: 'fpt-key-vault/create-policy', label: 'Policyの作成' },
                { type: 'doc', id: 'fpt-key-vault/delete-policy', label: 'Policyの削除' },
              ],
            },
            {
              type: 'category',
              label: 'Auth Method管理',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-key-vault/auth-method-management', label: 'Auth Method管理' },
                { type: 'doc', id: 'fpt-key-vault/create-auth-method', label: 'Auth Methodの作成' },
                { type: 'doc', id: 'fpt-key-vault/create-role', label: 'Roleの作成' },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'FPT ArgoCD',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-argocd/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'fpt-argocd/check-service-package-info', label: 'サービスパッケージ情報の確認' },
            { type: 'doc', id: 'fpt-argocd/create-fpt-argocd', label: 'FPT ArgoCDの新規作成' },
            { type: 'doc', id: 'fpt-argocd/view-argocd-detail', label: 'ArgoCD詳細の表示' },
            { type: 'doc', id: 'fpt-argocd/add-cluster-to-argocd', label: 'Clusterの追加' },
            {
              type: 'category',
              label: '設定 (Configure)',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-argocd/configure-image-updater', label: 'Image Updaterの設定' },
                { type: 'doc', id: 'fpt-argocd/enable-disable-images-updater', label: 'Image Updaterの有効化/無効化' },
                { type: 'doc', id: 'fpt-argocd/configure-log-level', label: 'Log Levelの設定' },
                { type: 'doc', id: 'fpt-argocd/manage-secrets', label: 'Secretsの管理' },
                { type: 'doc', id: 'fpt-argocd/manage-registry-secrets', label: 'Registry Secretsの管理' },
                { type: 'doc', id: 'fpt-argocd/manage-container-registry', label: 'Container Registryの管理' },
                { type: 'doc', id: 'fpt-argocd/configure-notifications', label: 'Notificationsの設定' },
                { type: 'doc', id: 'fpt-argocd/enable-disable-notifications', label: 'Notificationsの有効化/無効化' },
                { type: 'doc', id: 'fpt-argocd/configure-notification-channels', label: '通知チャンネルの設定' },
                { type: 'doc', id: 'fpt-argocd/configure-oidc-config', label: 'OIDCの設定' },
                { type: 'doc', id: 'fpt-argocd/configure-oidc-sso', label: 'OIDC SSOの設定' },
                { type: 'doc', id: 'fpt-argocd/enable-disable-oidc', label: 'OIDCの有効化/無効化' },
                { type: 'doc', id: 'fpt-argocd/update-oidc-config', label: 'OIDC設定の更新' },
                { type: 'doc', id: 'fpt-argocd/delete-oidc-config', label: 'OIDC設定の削除' },
                { type: 'doc', id: 'fpt-argocd/enable-applications-set', label: 'Applications Setの有効化' },
                { type: 'doc', id: 'fpt-argocd/enable-disable-admin-user', label: 'Admin Userの有効化/無効化' },
                { type: 'doc', id: 'fpt-argocd/enable-disable-anonymous-user', label: 'Anonymous Userの有効化/無効化' },
              ],
            },
            {
              type: 'category',
              label: 'Webhook',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-argocd/configure-webhook', label: 'Webhookの設定' },
                { type: 'doc', id: 'fpt-argocd/configure-webhook-with-secret', label: 'Webhook Secretの設定' },
                { type: 'doc', id: 'fpt-argocd/add-webhook-secret', label: 'Webhook Secretの追加' },
                { type: 'doc', id: 'fpt-argocd/edit-webhook-secret', label: 'Webhook Secretの編集' },
                { type: 'doc', id: 'fpt-argocd/delete-webhook-secret', label: 'Webhook Secretの削除' },
              ],
            },
            { type: 'doc', id: 'fpt-argocd/configure-build-options-kustomize', label: 'Kustomize Build Optionsの設定' },
            { type: 'doc', id: 'fpt-argocd/configure-timereconcile', label: 'TimeReconcileの設定' },
            { type: 'doc', id: 'fpt-argocd/configure-rbac', label: 'RBACポリシーの設定' },
            { type: 'doc', id: 'fpt-argocd/configure-whitelist-ip', label: 'Whitelist IPの設定' },
            { type: 'doc', id: 'fpt-argocd/upgrade-service-package', label: 'サービスパッケージのアップグレード' },
            { type: 'doc', id: 'fpt-argocd/upgrade-version', label: 'ArgoCDバージョンのアップグレード' },
            {
              type: 'category',
              label: 'アカウント管理 (Manage Accounts)',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-argocd/manage-accounts', label: 'アカウント管理' },
                { type: 'doc', id: 'fpt-argocd/manage-admin-account', label: 'Admin Accountの管理' },
                { type: 'doc', id: 'fpt-argocd/manage-admin-account-enable-disable-anonymous-user', label: 'Anonymous Userの管理' },
                { type: 'doc', id: 'fpt-argocd/update-admin-password', label: 'Adminパスワードの更新' },
                { type: 'doc', id: 'fpt-argocd/create-account', label: 'アカウントの作成' },
                { type: 'doc', id: 'fpt-argocd/edit-capabilities', label: '権限の編集' },
                { type: 'doc', id: 'fpt-argocd/change-password', label: 'パスワードの変更' },
                { type: 'doc', id: 'fpt-argocd/enable-disable-account', label: 'アカウントの有効化/無効化' },
              ],
            },
            { type: 'doc', id: 'fpt-argocd/demo', label: 'Demo' },
          ],
        },
      ],
    },
    // ========== FPT Monitoring ==========
    {
      type: 'category',
      label: 'FPT Monitoring',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'インシデント管理 (Incident Management)',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'incident-management/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'incident-management/create-incident', label: 'インシデントの作成' },
            { type: 'doc', id: 'incident-management/declare-incident', label: 'インシデントの宣言' },
            { type: 'doc', id: 'incident-management/create-incident-via-webhook', label: 'Webhook経由でのインシデント作成' },
            { type: 'doc', id: 'incident-management/manage-incidents', label: 'インシデントの管理' },
            { type: 'doc', id: 'incident-management/filter-incidents', label: 'インシデントのフィルタリング' },
            { type: 'doc', id: 'incident-management/view-incident-detail', label: 'インシデント詳細の表示' },
            { type: 'doc', id: 'incident-management/change-the-incident-status', label: 'ステータスの変更' },
            { type: 'doc', id: 'incident-management/change-the-incident-severity', label: '重大度の変更' },
            { type: 'doc', id: 'incident-management/post-incident-activity', label: 'インシデント後のアクティビティ' },
            { type: 'doc', id: 'incident-management/copy-activities-as-markdown', label: 'アクティビティのMarkdownコピー' },
            { type: 'doc', id: 'incident-management/incident-data-visualization', label: 'データの可視化' },
            { type: 'doc', id: 'incident-management/incident-status', label: 'ステータス一覧' },
            { type: 'doc', id: 'incident-management/incident-severity', label: '重大度一覧' },
            { type: 'doc', id: 'incident-management/incident-label', label: 'ラベル管理' },
            { type: 'doc', id: 'incident-management/configure-incident-settings', label: '設定の構成' },
            {
              type: 'category',
              label: 'インテグレーション (Integrations)',
              collapsed: true,
              items: [
                { type: 'doc', id: 'incident-management/configure-integrations', label: 'インテグレーションの設定' },
                { type: 'doc', id: 'incident-management/microsoft-teams', label: 'Microsoft Teams' },
                { type: 'doc', id: 'incident-management/slack', label: 'Slack' },
                { type: 'doc', id: 'incident-management/telegram', label: 'Telegram' },
                { type: 'doc', id: 'incident-management/atlassian-jira', label: 'Atlassian Jira' },
                { type: 'doc', id: 'incident-management/grafana-webhook', label: 'Grafana Webhook' },
                { type: 'doc', id: 'incident-management/incoming-webhook', label: 'Incoming Webhook' },
                { type: 'doc', id: 'incident-management/outgoing-webhook', label: 'Outgoing Webhook' },
              ],
            },
          ],
        },
      ],
    },
    // ========== FPT Security ==========
    {
      type: 'category',
      label: 'FPT Security',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'IAM (Identity & Access Management)',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'iam/initial-setup', label: '初期設定' },
            {
              type: 'category',
              label: 'ロール管理 (Role Management)',
              collapsed: true,
              items: [
                { type: 'doc', id: 'iam/role-management', label: 'ロール管理' },
                { type: 'doc', id: 'iam/role-overview', label: '概要' },
                { type: 'doc', id: 'iam/view-role-list', label: 'ロール一覧' },
                { type: 'doc', id: 'iam/create-role', label: 'ロールの作成と権限の割り当て' },
                { type: 'doc', id: 'iam/view-role-detail', label: 'ロールの詳細' },
                { type: 'doc', id: 'iam/edit-role', label: 'ロールと権限の編集' },
                { type: 'doc', id: 'iam/delete-role', label: 'ロールの削除' },
              ],
            },
            {
              type: 'category',
              label: 'ユーザーグループ管理 (User Group)',
              collapsed: true,
              items: [
                { type: 'doc', id: 'iam/user-group-management', label: 'ユーザーグループ管理' },
                { type: 'doc', id: 'iam/user-group-overview', label: '概要' },
                { type: 'doc', id: 'iam/create-user-group', label: 'ユーザーグループの作成' },
                { type: 'doc', id: 'iam/view-user-group-list', label: 'ユーザーグループ一覧' },
                { type: 'doc', id: 'iam/view-user-group-detail', label: 'ユーザーグループの詳細' },
                { type: 'doc', id: 'iam/edit-user-group', label: 'ユーザーグループの編集' },
                { type: 'doc', id: 'iam/delete-user-group', label: 'ユーザーグループの削除' },
              ],
            },
            {
              type: 'category',
              label: 'IAMユーザー管理 (IAM Users)',
              collapsed: true,
              items: [
                { type: 'doc', id: 'iam/iam-user-management', label: 'IAMユーザー管理' },
                { type: 'doc', id: 'iam/iam-user-overview', label: '概要' },
                { type: 'doc', id: 'iam/invite-iam-user', label: 'IAMユーザーの招待' },
                { type: 'doc', id: 'iam/create-account-access-vpc', label: 'アカウント作成とVPCアクセス' },
                { type: 'doc', id: 'iam/change-password', label: 'パスワード変更' },
                { type: 'doc', id: 'iam/configure-2fa', label: '2FA設定' },
              ],
            },
            {
              type: 'category',
              label: 'IPアクセス (IP Access)',
              collapsed: true,
              items: [
                { type: 'doc', id: 'iam/ip-access', label: 'IPアクセス' },
                { type: 'doc', id: 'iam/ip-access-overview', label: '概要' },
                { type: 'doc', id: 'iam/create-ip-access', label: 'IPアクセスレコードの作成' },
                { type: 'doc', id: 'iam/delete-ip-access', label: 'IPアクセスレコードの削除' },
                { type: 'doc', id: 'iam/ip-access-activity-log', label: 'アクティビティログ' },
                { type: 'doc', id: 'iam/download-access-log', label: 'アクセスログのダウンロード' },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'FPT Cloud WAF',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'fpt-cloud-waf/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'fpt-cloud-waf/add-waf-server', label: 'WAFサーバーの追加' },
            { type: 'doc', id: 'fpt-cloud-waf/log-in-waf-dashboard', label: 'WAF Dashboardへのログイン' },
            { type: 'doc', id: 'fpt-cloud-waf/configure-waf-server-connection', label: 'WAFサーバー接続の設定' },
            { type: 'doc', id: 'fpt-cloud-waf/monitor-waf-dashboard-overview', label: 'Dashboard Overviewでの監視' },
            { type: 'doc', id: 'fpt-cloud-waf/edit-waf-server', label: 'WAFサーバーの編集' },
            { type: 'doc', id: 'fpt-cloud-waf/delete-waf-server', label: 'WAFサーバーの削除' },
            {
              type: 'category',
              label: 'Proxy Host',
              collapsed: true,
              items: [
                { type: 'doc', id: 'fpt-cloud-waf/manage-proxy-host', label: 'Proxy Hostの管理' },
                { type: 'doc', id: 'fpt-cloud-waf/create-proxy-host', label: 'Proxy Hostの作成' },
                { type: 'doc', id: 'fpt-cloud-waf/view-proxy-host-detail', label: 'Proxy Hostの詳細' },
                { type: 'doc', id: 'fpt-cloud-waf/update-proxy-host', label: 'Proxy Hostの更新' },
                { type: 'doc', id: 'fpt-cloud-waf/enable-disable-proxy-host', label: 'Proxy Hostの有効化/無効化' },
                { type: 'doc', id: 'fpt-cloud-waf/delete-proxy-host', label: 'Proxy Hostの削除' },
              ],
            },
            { type: 'doc', id: 'fpt-cloud-waf/manage-redirection-host', label: 'Redirection Hostの管理' },
            { type: 'doc', id: 'fpt-cloud-waf/add-stream-host', label: 'Stream Hostの追加' },
            { type: 'doc', id: 'fpt-cloud-waf/manage-404-host', label: '404 Hostの管理' },
            { type: 'doc', id: 'fpt-cloud-waf/manage-access-list', label: 'Access Listの管理' },
            { type: 'doc', id: 'fpt-cloud-waf/manage-ssl-certificates', label: 'SSL証明書の管理' },
            { type: 'doc', id: 'fpt-cloud-waf/manage-security-rule-sets', label: 'Security Rule Setsの管理' },
            { type: 'doc', id: 'fpt-cloud-waf/manage-waf-dashboard-users', label: 'WAF Dashboardユーザーの管理' },
            { type: 'doc', id: 'fpt-cloud-waf/tutorials-add-waf-server', label: 'チュートリアル: WAFサーバーの追加' },
            { type: 'doc', id: 'fpt-cloud-waf/tutorials-log-in-waf-dashboard', label: 'チュートリアル: WAF Dashboardへのログイン' },
          ],
        },
      ],
    },
    // ========== Billing ==========
    {
      type: 'category',
      label: '請求 (Billing)',
      collapsed: true,
      items: [
        
            { type: 'doc', id: 'cost-explorer/コストエクスプローラー', label: 'コストエクスプローラー' },
            { type: 'doc', id: 'cost-explorer/サービス別のダッシュボード＆コストの確認_1', label: 'サービス別のコストを確認' },
            { type: 'doc', id: 'cost-explorer/フィルタをカスタマイズして期間／リソース グループ別のコストを確認_2', label: 'リソースタイプ別のコストを確認' },
            { type: 'doc', id: 'cost-explorer/質問-1', label: 'コストエクスプローラーを確認できない' },
            { type: 'doc', id: 'cost-explorer/質問-2', label: '特定リソースでフィルタリング' }
          ,
        
            { type: 'doc', id: 'budget-alert/予算アラート', label: '予算アラート' },
            { type: 'doc', id: 'budget-alert/予算アラートの作成_1', label: '予算アラートの作成' },
            { type: 'doc', id: 'budget-alert/コスト情報とアラート履歴の確認_2', label: 'コスト情報とアラート履歴の確認' },
            { type: 'doc', id: 'budget-alert/予算アラートの無効化_3', label: '予算アラートの一時停止' },
            { type: 'doc', id: 'budget-alert/予算アラートの編集_4', label: '予算アラートの編集' },
            { type: 'doc', id: 'budget-alert/予算アラートの削除_5', label: '予算アラートの削除' },
            { type: 'doc', id: 'budget-alert/予算しきい値に達した後の新規コンピューティング／ネットワークリソースの作成制限_6', label: 'しきい値到達時のリソース作成制限' }
          ,
      ],
    },
    // ========== Support ==========
    {
      type: 'category',
      label: 'サポート (Support)',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Trellix Customer Guide',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'trellix-customer-guide/trellix-customer-guide', label: 'Trellix カスタマーガイド' },
            { type: 'doc', id: 'trellix-customer-guide/truy-cap-giao-dien-quan-tri', label: '管理インターフェースへのアクセス' },
            { type: 'doc', id: 'trellix-customer-guide/setting-agert', label: 'agent インストールパッケージの作成' },
            { type: 'doc', id: 'trellix-customer-guide/client-task', label: 'クライアントタスクの管理' },
            { type: 'doc', id: 'trellix-customer-guide/report', label: 'レポートの表示' },
            { type: 'doc', id: 'trellix-customer-guide/view-log', label: 'ログの表示' }
          ],
        },
      ],
    },
    // ========== FPT AI Factory ==========
    {
      type: 'category',
      label: 'FPT AIファクトリー (AI Factory)',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'AI Factory Billing',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'ai-factory-billing/ai-factory-billing', label: 'AI Factory Billing' },
            { type: 'doc', id: 'ai-factory-billing/overview', label: '概要' },
            { type: 'doc', id: 'ai-factory-billing/quick-start', label: 'クイックスタート' },
            { type: 'doc', id: 'ai-factory-billing/balance', label: '残高' },
            { type: 'doc', id: 'ai-factory-billing/low-balance-threshold-alert', label: '低残高アラート' },
            { type: 'doc', id: 'ai-factory-billing/credit-history', label: 'クレジット履歴' },
            { type: 'doc', id: 'ai-factory-billing/voucher-list', label: 'バウチャー一覧' },
            { type: 'doc', id: 'ai-factory-billing/payment-methods', label: '支払い方法' },
            { type: 'doc', id: 'ai-factory-billing/billing-calculation', label: '課金計算' },
            { type: 'doc', id: 'ai-factory-billing/gpu-container-billing', label: 'GPU Container 課金' },
            { type: 'doc', id: 'ai-factory-billing/model-hub-billing', label: 'Model Hub 課金' },
            { type: 'doc', id: 'ai-factory-billing/model-finetuning-billing', label: 'Model Fine-Tuning 課金' },
            { type: 'doc', id: 'ai-factory-billing/modas-billing', label: 'MoDaS 課金' },
            { type: 'doc', id: 'ai-factory-billing/add-credits', label: 'クレジットの追加' },
            { type: 'doc', id: 'ai-factory-billing/redeem-voucher', label: 'バウチャーの引き換え' },
            { type: 'doc', id: 'ai-factory-billing/payment-invoice', label: '支払い請求書' },
            { type: 'doc', id: 'ai-factory-billing/billing-plan', label: '課金プラン' },
            { type: 'doc', id: 'ai-factory-billing/billing-faq', label: 'よくある質問（Billing FAQ）' }
          ],
        },
        
            { type: 'doc', id: 'ai-notebook/ai-notebook-jp', label: 'AI Notebook' },
            { type: 'doc', id: 'ai-notebook/get-started-jp', label: 'AI Notebookについて' },
            { type: 'doc', id: 'ai-notebook/quick-start-jp', label: 'クイックスタート' },
            { type: 'doc', id: 'ai-notebook/lauch-jp', label: 'AI Notebookの起動' },
            { type: 'doc', id: 'ai-notebook/create-jp', label: 'Notebookの作成' },
            { type: 'doc', id: 'ai-notebook/switch', label: 'Kernelの接続と切り替え' },
            { type: 'doc', id: 'ai-notebook/shut-down-jp', label: 'Kernelのシャットダウン' },
            { type: 'doc', id: 'ai-notebook/faq-jp', label: 'よくある質問' }
          ,
        
            { type: 'doc', id: 'ai_marketplace/ai_marketplace', label: 'AI Marketplace' },
            { type: 'doc', id: 'ai_marketplace/overview', label: '概要' },
            { type: 'doc', id: 'ai_marketplace/quick-start', label: 'クイックスタート' },
            { type: 'doc', id: 'ai_marketplace/home-page', label: 'ホームページ' },
            { type: 'doc', id: 'ai_marketplace/product-information', label: '製品情報' },
            { type: 'doc', id: 'ai_marketplace/playground', label: 'Playground' },
            { type: 'doc', id: 'ai_marketplace/fine-tune-with-lora', label: 'LoRA でファインチューニング' },
            { type: 'doc', id: 'ai_marketplace/deployment-lora-inference', label: 'LoRA 推論のデプロイ' },
            { type: 'doc', id: 'ai_marketplace/my-account', label: 'マイアカウント' },
            { type: 'doc', id: 'ai_marketplace/balance', label: '残高' },
            { type: 'doc', id: 'ai_marketplace/billing', label: '請求' },
            { type: 'doc', id: 'ai_marketplace/contact-us', label: 'お問い合わせ' },
            { type: 'doc', id: 'ai_marketplace/how-to-create-an-api-key', label: 'API キーの作成' },
            { type: 'doc', id: 'ai_marketplace/api-integration', label: 'API 連携' },
            { type: 'doc', id: 'ai_marketplace/deprecated-models', label: '廃止モデル' },
            { type: 'doc', id: 'ai_marketplace/FAQ', label: 'FAQ' },
            { type: 'doc', id: 'ai_marketplace/sign-in', label: 'サインイン' }
          ,
        
            { type: 'doc', id: 'data-hub/data-hub', label: 'Data Hub' },
            { type: 'doc', id: 'data-hub/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'data-hub/create-connection', label: '接続の作成' },
            { type: 'doc', id: 'data-hub/generate-dataset', label: 'データセットの生成' }
          ,
        {
          type: 'category',
          label: 'Model Serving',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'model-serving/model-serving', label: 'Model Serving' },
            { type: 'doc', id: 'model-serving/general-intro-model-serving', label: '概要' },
            { type: 'doc', id: 'model-serving/initial-set-up', label: '初期設定' },
            { type: 'doc', id: 'model-serving/terms-definitions', label: '用語と定義' },
            { type: 'doc', id: 'model-serving/about-fci', label: 'FCIについて' },
            { type: 'doc', id: 'model-serving/deployment-list', label: 'デプロイメント一覧' },
            { type: 'doc', id: 'model-serving/create-a-new-model-serving-deployment', label: '新規デプロイメントの作成' },
            { type: 'doc', id: 'model-serving/deployment-configuration-information', label: 'デプロイメント設定' },
            { type: 'doc', id: 'model-serving/detailed-configuration-information', label: '詳細設定' },
            { type: 'doc', id: 'model-serving/traffic-setting-configuration-information', label: 'トラフィック設定' },
            { type: 'doc', id: 'model-serving/status-actions-deployment', label: 'ステータスとアクション' },
            { type: 'doc', id: 'model-serving/delete-a-deployment', label: 'デプロイメントの削除' }
          ],
        },
        
            { type: 'doc', id: 'model-fine-tuning/model-fine-tuning-ja', label: 'モデルの微調整' },
            { type: 'doc', id: 'model-fine-tuning/concept', label: 'モデルの微調整' },
            { type: 'doc', id: 'model-fine-tuning/key-features', label: 'Key Features' },
            { type: 'doc', id: 'model-fine-tuning/faqs', label: 'よくある質問' },
            { type: 'doc', id: 'model-fine-tuning/initial-setup', label: '初期設定' },
            { type: 'doc', id: 'model-fine-tuning/top-up-balance', label: 'Top Up Balance' },
            { type: 'doc', id: 'model-fine-tuning/create-pipeline', label: 'Create Pipeline' },
            { type: 'doc', id: 'model-fine-tuning/training-configuration', label: 'Training Configuration' },
            { type: 'doc', id: 'model-fine-tuning/select-data-format', label: 'Select Data Format' },
            { type: 'doc', id: 'model-fine-tuning/set-hyperparameters', label: 'Set Hyperparameters' },
            { type: 'doc', id: 'model-fine-tuning/start-pipeline', label: 'Start Pipeline' },
            { type: 'doc', id: 'model-fine-tuning/manage-pipeline', label: 'Manage Pipeline' },
            { type: 'doc', id: 'model-fine-tuning/view-pipeline-settings', label: 'モデルの微調整' },
            { type: 'doc', id: 'model-fine-tuning/audit-logs', label: 'モデルの微調整' },
            { type: 'doc', id: 'model-fine-tuning/view-execution-history', label: 'View Execution History' },
            { type: 'doc', id: 'model-fine-tuning/view-execution-details', label: 'View Execution Details' }
          ,
        
            { type: 'doc', id: 'gpu-virtual-machine-en/gpu-virtual-machine', label: 'GPU Virtual Machine' },
            { type: 'doc', id: 'gpu-virtual-machine-en/概要', label: '概要' },
            { type: 'doc', id: 'gpu-virtual-machine-en/初期-設定', label: '初期 設定' },
            { type: 'doc', id: 'gpu-virtual-machine-en/クイック-スタート', label: 'クイック スタート' },
            { type: 'doc', id: 'gpu-virtual-machine-en/サブネット-の-作成', label: 'サブネット の 作成' },
            { type: 'doc', id: 'gpu-virtual-machine-en/GPU-VM -インスタンス-の-作成', label: 'Gpu Vm インスタンス の...' },
            { type: 'doc', id: 'gpu-virtual-machine-en/IPアドレス（フローティングIP）の割り当て', label: 'Ipアドレス（フローティングIp）の割り当て' },
            { type: 'doc', id: 'gpu-virtual-machine-en/セキュリティグループの作成', label: 'セキュリティグループの作成' },
            { type: 'doc', id: 'gpu-virtual-machine-en/サーバーへのアクセス', label: 'サーバーへのアクセス' },
            { type: 'doc', id: 'gpu-virtual-machine-en/に関するよくある質問', label: '一般' }
          ,
        
            { type: 'doc', id: 'モデルテスト/モデルテスト', label: 'モデルテスト' },
            { type: 'doc', id: 'モデルテスト/definition', label: 'モデルテスト' },
            { type: 'doc', id: 'モデルテスト/key-features', label: 'Key Features' },
            { type: 'doc', id: 'モデルテスト/create-an-interactive-session', label: 'モデルテストサービスにアクセスし、「インタラクティブセッション」を選択し、「新しいセッションを作成」をクリックします [![file](/img/migrated/image-1746688925988.21.46-ae14f354.png)](/img/migrated/image-1746688925988.21.46-ae14f354.png)' },
            { type: 'doc', id: 'モデルテスト/test-models-response', label: 'Test Models Response' },
            { type: 'doc', id: 'モデルテスト/completion-history', label: 'Completion History' }
          ,
        {
          type: 'category',
          label: 'ユーザートークン (User Token)',
          className: 'sidebar-migrated',
          collapsed: true,
          items: [
            { type: 'doc', id: 'user-token/user-token', label: 'ユーザートークン' },
            { type: 'doc', id: 'user-token/overview', label: '概要' },
            { type: 'doc', id: 'user-token/quick-start', label: 'クイックスタート' },
            { type: 'doc', id: 'user-token/how-to-create-an-user-token', label: 'ユーザートークンの作成方法' }
          ],
        },
      ],
    },
  ],
};
