  {
    type: 'category',
    label: 'FPT Data Platform',
    items: [
      'fpt-data-platform/initial-setup/initial-setup',
      {
        type: 'category',
        label: 'Workspace',
        items: [
          'fpt-data-platform/workspace/index',
          'fpt-data-platform/workspace/tao-workspace',
          'fpt-data-platform/workspace/xem-thong-tin-workspace',
          'fpt-data-platform/workspace/xoa-workspace',
          'fpt-data-platform/workspace/keystore-management',
          'fpt-data-platform/workspace/certificate-manager',
          'fpt-data-platform/workspace/monitoring',
        ],
      },
      {
        type: 'category',
        label: 'CDC Service',
        items: [
          'fpt-data-platform/cdc-service/index',
          'fpt-data-platform/cdc-service/tao-cdc-service',
          'fpt-data-platform/cdc-service/xem-thong-tin-cdc-service',
          'fpt-data-platform/cdc-service/postgresql-source-connector',
          'fpt-data-platform/cdc-service/mongoDB-source-connector',
          'fpt-data-platform/cdc-service/sql-server-source-connector',
          'fpt-data-platform/cdc-service/mysql-source-connector',
          'fpt-data-platform/cdc-service/mariadb-source-connector',
          'fpt-data-platform/cdc-service/oracle-source-connector',
          'fpt-data-platform/cdc-service/clickhouse-logs-sink-connector',
          'fpt-data-platform/cdc-service/mongodb-sink-connector',
          'fpt-data-platform/cdc-service/postgresql-sink-connector',
          'fpt-data-platform/cdc-service/opensearch-sink-connector',
          'fpt-data-platform/cdc-service/sql-server-sink-connector',
          'fpt-data-platform/cdc-service/mysql-sink-connector',
          'fpt-data-platform/cdc-service/mariadb-sink-connector',
          'fpt-data-platform/cdc-service/iceberg-sink-connector',
          'fpt-data-platform/cdc-service/clickhouse-replication-sink-connector',
          'fpt-data-platform/cdc-service/s3-sink-connector',
          'fpt-data-platform/cdc-service/elasticsearch-sink-connector',
          'fpt-data-platform/cdc-service/iceberg-logs-sink-connector',
          'fpt-data-platform/cdc-service/redis-sink-connector',
          'fpt-data-platform/cdc-service/tao-connector-source-kafka',
          'fpt-data-platform/cdc-service/tao-connector-source-s3',
          'fpt-data-platform/cdc-service/xem-thong-tin-connector',
          'fpt-data-platform/cdc-service/hanh-dong-voi-connector',
          'fpt-data-platform/cdc-service/xoa-connector',
          'fpt-data-platform/cdc-service/xem-thong-tin-snapshot',
          'fpt-data-platform/cdc-service/trang-thai-snapshot',
          'fpt-data-platform/cdc-service/hanh-dong-voi-snapshot',
          'fpt-data-platform/cdc-service/xoa-cdc-service',
          'fpt-data-platform/cdc-service/kafka-mm2',
        ],
      },
      {
        type: 'category',
        label: 'Apache Superset',
        items: [
          'fpt-data-platform/superset/index',
          'fpt-data-platform/superset/tao-superset',
          'fpt-data-platform/superset/xem-thong-tin-superset',
          'fpt-data-platform/superset/xoa-superset',
        ],
      },
      {
        type: 'category',
        label: 'JupyterHub',
        items: [
          'fpt-data-platform/jupyterhub/index',
          'fpt-data-platform/jupyterhub/tao-Jupyterhub',
          'fpt-data-platform/jupyterhub/xem-thong-tin-juperterhub',
          'fpt-data-platform/jupyterhub/xoa-jupyterhub',
          'fpt-data-platform/jupyterhub/them-nguoi-dung',
          'fpt-data-platform/jupyterhub/tao-profile',
          'fpt-data-platform/jupyterhub/phan-quyen-nguoi-dung-su-dung-profile',
          'fpt-data-platform/jupyterhub/dbt',
        ],
      },
      {
        type: 'category',
        label: 'Ranger',
        items: [
          'fpt-data-platform/ranger/index',
          'fpt-data-platform/ranger/tao-ranger',
          'fpt-data-platform/ranger/xem-ranger',
          'fpt-data-platform/ranger/cau-hinh-va-quan-ly-query-engine',
          'fpt-data-platform/ranger/tag-sync',
          'fpt-data-platform/ranger/xoa-ranger',
        ],
      },
      {
        type: 'category',
        label: 'Hive Metastore',
        items: [
          'fpt-data-platform/hive-metastore/index',
          'fpt-data-platform/hive-metastore/tao-hive-metastore',
          'fpt-data-platform/hive-metastore/xem-thong-tin-hive-metastore',
          'fpt-data-platform/hive-metastore/xoa-hive-metastore',
        ],
      },
      {
        type: 'category',
        label: 'Query Engine',
        items: [
          'fpt-data-platform/query-engine/index',
          'fpt-data-platform/query-engine/tao-query-engine',
          'fpt-data-platform/query-engine/xem-thong-tin-query-engine',
          'fpt-data-platform/query-engine/xoa-query-engine',
          'fpt-data-platform/query-engine/quan-ly-connectors',
          'fpt-data-platform/query-engine/quan-ly-users',
          'fpt-data-platform/query-engine/quan-ly-Policies',
        ],
      },
      {
        type: 'category',
        label: 'Nessie',
        items: [
          'fpt-data-platform/nessie/index',
          'fpt-data-platform/nessie/tao-nessie',
          'fpt-data-platform/nessie/xem-thong-tin-nessie',
          'fpt-data-platform/nessie/xoa-nessie',
        ],
      },
      {
        type: 'category',
        label: 'Flink',
        items: [
          'fpt-data-platform/flink/index',
          'fpt-data-platform/flink/tao-apache-flink',
          'fpt-data-platform/flink/xem-thong-tin-apache-flink',
          'fpt-data-platform/flink/xoa-apache-flink',
        ],
      },
      {
        type: 'category',
        label: 'Orchestration',
        items: [
          'fpt-data-platform/orchestration/index',
          'fpt-data-platform/orchestration/tao-airflow',
          'fpt-data-platform/orchestration/xem-thong-tin-orchestration',
          'fpt-data-platform/orchestration/xoa-orchestration',
          'fpt-data-platform/orchestration/huong-dan-airflow-dbt',
          'fpt-data-platform/orchestration/huong-dan-airflow-my-workspace',
          'fpt-data-platform/orchestration/huong-dan-airflow-job-submit',
          'fpt-data-platform/orchestration/huong-dan-secert-backends',
          'fpt-data-platform/orchestration/huong-dan-airflow-workflow',
        ],
      },
      {
        type: 'category',
        label: 'Ingestion Service',
        items: [
          'fpt-data-platform/ingestion/index',
          'fpt-data-platform/ingestion/tao-ingestion',
          'fpt-data-platform/ingestion/xem-thong-tin-ingestion',
          'fpt-data-platform/ingestion/xoa-ingestion',
          'fpt-data-platform/ingestion/chinh-sua-ingestion',
        ],
      },
      {
        type: 'category',
        label: 'Processing Service',
        items: [
          'fpt-data-platform/processing/index',
          'fpt-data-platform/processing/tao-processing-service',
          'fpt-data-platform/processing/xem-thong-tin-processing-service',
          'fpt-data-platform/processing/xoa-processing-service',
          'fpt-data-platform/processing/quan-ly-compute',
          'fpt-data-platform/processing/quan-ly-image-cua-compute',
        ],
      },
      {
        type: 'category',
        label: 'Open Metadata',
        items: [
          'fpt-data-platform/open-metadata/index',
          'fpt-data-platform/open-metadata/tao-open-metadata-service',
          'fpt-data-platform/open-metadata/xem-thong-tin-open-metadata-service',
          'fpt-data-platform/open-metadata/cap-nhat-open-metadata',
          'fpt-data-platform/open-metadata/xoa-open-metadata',
          'fpt-data-platform/open-metadata/huong-dan-su-dung-open-metadata',
        ],
      },
    ],
  },
